### ISSUE TITLE
Promoting Additional Releases of OpenToonz 

### ISSUE THREAD

**Issue by Bugsbane** [opentoonz/opentoonz#1444]
Hi there,

Given that I'm already able to download a .appimage Linux package which runs on just about any Linux distro out there, I find it odd that there isn't even mention of Linux availability on the download page. I mean, the work to create an AppImage is negligible compared to the work already done to make OpenToonz able to be compiled and run on Linux.

So can we please get some kind of Linux package available to download from the download page along with the Mac and Windows packages?

**Comment by morevnaproject** [comment]
I have submitted a pull request to include Linux version to the frontpage 11 months ago - https://github.com/opentoonz/opentoonz.github.io/pull/11

@shun-iwasawa Can you please take a look and tell about your concerns? ^__^

**Comment by q2dg** [comment]
The lack of interest in this trivial issue is astonishingly disappointing

**Comment by Bugsbane** [comment]
Mind blowing.

**Comment by RodneyBaker** [comment]
In thinking about this more perhaps a new html page might be created that lists unofficially forks and branches and that page can gain a link via the main OpenToonz download page.

The primary issue then would not be one of indicating any degree of support but would rather be one of keeping the page up to date with a proper link to those that officially support the resource.

Not sure what the best way forward is... just throwing out the idea.

**Comment by Orphanlast** [comment]
I'll mention this in an OT News Video.

However, doesn't Opentoonz show up in the Repository? Opentoonz notifies you when there's an update. Does it not take you to the download page, direct?

I genuinely don't know. I suck at Linux, but I have used it as a primary OS before, in the past, and I have no current knowledge about how Opentoonz is on Linux, other than, people are working on improving its performance on Linux

**Comment by Bugsbane** [comment]
Even just a link to the flatpack file with a disclaimer... That's all Linux users need to get started. It can be expanded from there, but just a link with the disclaimer text would:

a) Let people know that a Linux build existed
b) Let them get started using it regardless of their distro
c) Make it clear that it was unsupported

How hard is a link and a sentence or two to add to the download page?

**Comment by jpturcotte** [comment]
The repo for the website is here: https://github.com/opentoonz/opentoonz.github.io. Why not try opening a pull request?

**Comment by RodneyBaker** [comment]
The following (plus a few more) likely need to be mentioned as unofficially supported releases when we do finally get that page published:

- [ ] Morevna (Linux, Mac and PC)
- [ ] 32bit Windows
- [ ] OTX (Windows portable)
- [ ] Flat Pak (wide variety of platforms - Linux based)
- [ ] Snap (Linux)
- [ ] OpenToonz github AppVeyor (Windows) Not officially supported but a byproduct of official builds

Who am I missing? (Probably someone obvious)

**Comment by xenogenesi** [comment]
> Who am I missing? (Probably someone obvious)

How about getting opentoonz into an official distro repository (like Debian, any derivate distro would inherit it, see ubuntu mint ...)

I don't know the process to get it included but if there aren't issues with the licenses (proprietary/commercial) there aren't reason to not include it.

**Comment by RodneyBaker** [comment]
Closing as a more appropriate place for adding the information is one (or both) of the following:

https://github.com/opentoonz/opentoonz.github.io

https://github.com/opentoonz/opentoonz_docs

**Comment by q2dg** [comment]
Done

**Comment by RodneyBaker** [comment]
@gab3d  As you are heavily involved in updating the online Opentoonz documenation perhaps you are the ideal person to query about a section of the documentation that would link to unofficially supported Opentoonz releases.

My thinking is that a section such as this would suffice:
https://opentoonz.readthedocs.io/en/latest/unofficial_releases.html

Recommenation:  Any release that cannot maintain a dedicated and permanent link to their release should NOT be listed.

For continuing discussion on this request see:  
https://github.com/opentoonz/opentoonz.github.io/issues/56

**Comment by gab3d** [comment]
I have no problem to do it.
Still, there already are links to the Morevna and other builds in the Linux installation page.
No OTX reference though...

**Comment by RodneyBaker** [comment]
Yes, I did see the installation sections outlining Morevna etc.
Those fulfill important How to Install instructions.
I was mostly thinking of the request for promotion of unofficial releases.

I'm not sure how best to approach that short of having a dedicated section for links.
This could be an 'Additional Resources' section at the end of the document or it could be a dedicated page for both official and unofficial releases.

I'll leave that to the experts (namely you @gab3d!) as I don't particularly have a preference outside of a desire to keep maintenance/editing of links to the absolute minimum possible so that others don't have to chase after broken links.

I'm also thinking of how this looks when the user uses the readthedocs site to generate a PDF.
Having the resources/links to all the various releases will fulfill the underlying desire to promote those releases and place them where they can easily be discovered.
