### ISSUE TITLE
v1.3 (New Version) Release Schedule

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#2386]
This is not an issue but for sharing a current plan of the next version release.

As of now I'm planning to release the next version (v 1.3) in late January 2019.
Here is my draft schedule:

- Mid-December, 2018  -  Freezing features ("new feature" PR posted after this will not be included in the new version)
- Two weeks for bug tracking & translation update
- The beginning of 2019  -  Release of v1.3 RC
- Two+ weeks for urgent bug fix or releasing RC2 if needed
- Late January 2019 - Release of v1.3

I would appreciate any comments or suggestions. Thank you!

**Comment by Orphanlast** [comment]
Cool stuff. Thumbs up.

**Comment by adamearle** [comment]
not to sound like a  broken record

svg? work flow sreeetch
svg? work flow sreeetch
svg? work flow sreeetch
svg? work flow sreeetch
svg? work flow sreeetch
svg? work flow sreeetch

should be working seamlessly

**Comment by RodneyBaker** [comment]
@adamearle  the primary SVG fixes required are just awaiting review and merging.
Getting close.

Glad to see the notice for the Release Schedule, Shun.
2018 has been a very good year.

**Comment by artisteacher** [comment]
Sounds good. I’d love to see some sort of organization option for the Raster brushes - maybe most recent brushes or most used brushes displaying at the top, or the capability to enable/disable different collections or etc. It would also be great to get a warning when selecting a style that is incompatible with the selected level. 

Also, a fix for #2303 on MacOS would be really helpful.

**Comment by gab3d** [comment]
@shun-iwasawa 
sounds perfect to me. ✌️ 
We should perhaps take the opportunity to change the name of the "Opentoonz 1.x stuff" folder to "Opentoonz 1 stuff" or something like that. I remember you mentioning how, currently, the inclusion of the revision (.x) number in that folder name, complicated somewhat the versioning scheme of OT.


@artisteacher 
...maybe a top section of "Favorite Brushes", coupled with a RMB option over every brush: "Mark as Favorite", to atomatically place it at the top?
There should also be a RMB option over favorite brushes (those at the proposed top section): "Remove from Favorite Brushes".

**Comment by manongjohn** [comment]
Oops. Sorry for accidental closure. Reopened. :)

I think the folder should just be "OpenToonz stuff". In addition, I'd like to see the executable just be called "OpenToonz.exe". Version number should really only be in opening splash screen and Help about. I don't mind it on the window frame.

**Comment by RodneyBaker** [comment]
As long as the user has the ability to rename the stuff and exe I agree that the locations and filenames could and very likely should be simplified.  Currently I don't think we can rename/relocate the install location or filename of the OpenToonz.exe file however.  The user does have the ability to rename the stuff directory so that change might be fairly trivial.

**Comment by manongjohn** [comment]
In Windows I rename the install folder all the time. I have running copies of official, nightly, otx and my own build. Just the stuff folder is common to all of them. You typically would need to create new desktop/startmenu shortcuts to each executable.

**Comment by artisteacher** [comment]
I also rename when installing a later release, but would love a faster way to get my settings back. It’s also a much bigger hassle if I update student computers myself & the stuff folder needs to be updated. On a related note, sometimes you need to update the qss or etc. in the stuff folder when doing a reinstall for everything to work/display properly. You’ll only know that if you read all of the release notes - which not everyone does.

**Comment by RodneyBaker** [comment]
PRs pending for next release (not complete)

Features
Text FX
- [ ] New Fx: Text Fx Iwa #2393 @shun-iwasawa

Schematic
- [ ] Schematic navigation enhancement #2175 @manongjohn 

Timeline Enhancements
- [ ] Duplicate in timeline #2342 @turtletooth 
- [ ] Allow Increase Step and Decrease Step to work even in selection is lost #2343 @turtletooth 
- [ ] Improved onion skin marker targeting #2378 @manongjohn 

Workflow Enhancement / Preferences
- [ ] Default and setting Interpolations #2344 @manongjohn 
- [ ] Allow Increase Step and Decrease Step to work even in selection is lost #2343 @turtletooth 

SVG fixes
- [ ] Fix svg stroke thickness #2358 opened 26 days ago by @Calabaraburus 
- [ ] Fix/Incorect svg arc parsing #2345 @Calabaraburus 

Crash Fixes
- [ ] Fix eraser mode switch crash #2396 @manongjohn 
- [ ] Fix moving note cells crash #2392 @manongjohn 
- [ ] Fix raster paste crash #2364 @manongjohn 
- [ ] Fix restoring eraser tool crash #2389 @manongjohn 
- [ ] Fix moving note cells crash #2392 @manongjohn 
- [ ] Fix raster crash after unhiding column #2369 @manongjohn 

Bugs
- [ ] Fix empty column property issues #2395  @manongjohn 
- [ ] Fix processing touchEvents after tablet events #2382 @manongjohn 
- [ ] Fix Current Frame on Load Level #2375 opened 20 days ago by @manongjohn 
- [ ] Fix wrong line cap loading #2374 opened 20 days ago by @manongjohn 
- [ ] Fix Hide/Lock shortcut bug #2365 opened 23 days ago by @manongjohn 

Tape Tool / Auto Inbetweening
- [ ] [WIP] Fix Vector Flipping on Using Tape Tool #2355 @shun-iwasawa 

SVG fixes
- [ ] Fix svg stroke thickness #2358  @Calabaraburus 
- [ ] Fix/Incorect svg arc parsing #2345 @Calabaraburus 

Antialiasing
- [ ] Fix antialiasing #2289 @ blackwarthog 

Memory Leak
- [ ] Fix small memory leak #2279 @otakuto

Refactoring and Optimization 
- [ ] Use bool instead of macro bool #2278 @otakuto 
- [ ] use std::unique_ptr instead of tcg::unique_ptr #2277 @otakuto 
- [ ] fix deterministic initialization #2273 @otakuto 

Linux
- [ ] Improve sound quality for playback and scrubbing on Linux #2244 @morevnaproject

**Comment by RodneyBaker** [comment]
This listing details some additional work and finer details in what has been accomplished since the last release:

(#2419)improve jpeg chroma subsampling 
(#2416)fix renaming psd cell 
(#2415)reload psd level 
(#2414)update travis qt version to 5.12.0 
(#2402)New Feature: Separate Colors   …
(#2394)update travis qt version 
(#2393) New Fx: Text Fx Iwa  …
(#2381)fix toonz raster brush crash 
(#2379)Fixed spelling mistake of "Flip Viewer Horizontally" 
(#2370)fix antialias to toonz raster levels 
(#2367)fix playback slowness with style editor 
(#2366)remove mysettings 
(#2362)Fix restoring raster tool crash 
(#2358)Fix svg stroke thickness   …
(#2352)fix tapetool crash 
(#2344)Default and setting Interpolations   …
(#2340) Made small pump tool sizes actually do something.  …
(#2337)open fx settings from xsheet 
(#2334)check folder access on save level 
(#2333)fix mesh visibility 
(#2332)fix toonzraster mypaint line with mouse 
(#2331)fix antialias undo 
(#2330)fix colormodel on high dpi monitor 
(#2326)fix import files with underscore 
(#2325)change temporary file name suffix 
(#2324)fix tfilepath 
(#2322)load jpeg dpi from exif, save to jfif 
(#2316)fix output preset 
(#2314)New Feature : Adding Clapperboard   …
(#2313)update qt version for travis ci 
(#2312)search for special folders tree 
(#2299)load palette global name on loading level 
(#2289)Fix antialiasing   …
(#2288)update viewer on opening 
(#2287)fix viewer size initialization 
(#2282) Fix processing MousePress and TabletPress events  …
(#2279)fix small memory leak 
(#2278)use bool instead of macro bool 
(#2277)use std::unique_ptr instead of tcg::unique_ptr 
(#2273)fix deterministic initialization 
(#2271)remove duplicate include 
(#2268)Timeline height and keyframe area adjustments   …
(#2264)fix updating animated guide 
(#2257)mypaint brush for toonz raster levels 
(#2247)Remove ON/OFF macro 
(#2246)use nullptr instead of Q_NULLPTR 
(#2245)simplify script   …
(#2241)schematic ui modification 
(#2240)shift and trace improvement 
(#2227)Fix font creation crash   …
(#2225)continue opening new scene after save levels 
(#2223)fix input field crash 
(#2222)fix type tool crash 
(#2212) Enhancement of the Shift and Trace Feature  …
(#2210)add linux desktop data 
(#2208)use xcode 8.3 on travis ci 
(#2199)rename xsheet cell with following level 
(#2197)use std::unique_ptr instead of std::auto_ptr 
(#2196)stage schematic multiple connect feature 
(#2195)using std::swap instead of tswap 
(#2194)ignore Thumbs.db 
(#2192)remove unnecessary schematic update 
(#2191)revert alt-dragging feature to fx schematic 
(#2188)fix display of motion path stroke 
(#2186)fix crash on merge 16bpc raster levels 
(#2184)fix load raster level with palette 
(#2183)fix crash on undo merge levels 
(#2174)fix crash on paste mesh node in stage schamatic 
(#2173)fix unc path conversion 
(#2165)use bool instead of macro bool 
(#2162)Fix spelling in one comment   …
(#2155)fix crash with command line arguments 
(#2153)fix license link 
(#2152)Enable Windows Ink Support   …
(#2151)fix frame range crash 
(#2143)set system path with command line qualifiers 
(#2134)force left to right layout 
(#2133)fix vector brush display bugs 
(#2126)convert old level files to tlv 
(#2125)fix viewer update on onionskin change 
(#2123)fix texture management 
(#2115)fix link fx 
(#2113)Testing PR instructions   …
(#2100)Fix old shortcuts   …
(#2080)Show actual fonts in font dropdowns   …
(#2034)Schematic UI Update  …

**Comment by RodneyBaker** [comment]
Special Thanks to:

Mr. Alvin Wong and the Krita Community for making the addition of Windows Ink possible.

**Comment by RodneyBaker** [comment]
For those of you inclined to testing we can always use good examples of current feature whether new to this release or otherwise.  Here's a rough example of what one thing the Text FX is useful for... credits:

(Disclaimer:  Actual credits are notional and based off of a quick grab and edit.  No slight intended for any one left out!) 

![creditrolla](https://user-images.githubusercontent.com/2576432/50309273-da2a7600-0463-11e9-9cef-d85a6dfbffd3.gif)

**Comment by RodneyBaker** [comment]
Thanks to @gab3d for updating documentation.

Thanks to @Savraska2 for updating installation procedures/links for unofficially supported releases.

Ref:  https://github.com/opentoonz/opentoonz_docs

**Comment by DarrenTAnims** [comment]
I've added a couple of small bugs (#2462 & #2463) and a couple of feature/expectations for the new text fx that might be worth squeezing in if you have time, to make it more complete.

https://groups.google.com/forum/#!category-topic/opentoonz_en/feature-requests/KJZtyDCsmgw
https://groups.google.com/forum/#!category-topic/opentoonz_en/feature-requests/B5iNkzLpl7E

**Comment by RodneyBaker** [comment]
@DarrenTAnims   While of interest, I wouldn't call #2462 and #2463 bugs especially as everything is working as intended but... over to Shun for that determination.  It looks to be a good proposal for development as feature and workflow enhancement.

**Comment by DarrenTAnims** [comment]
Understood @RodneyBaker .

**Comment by shun-iwasawa** [comment]
Following that no critical problem had been reported during RC2 period, I just released the official release of V1.3. 
Thanks to all of you for your contribution and feedback!
