### ISSUE TITLE
Discussion: Updating default preferences for new users

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#2523]
Watching a number of users on Twitch and other platforms struggling to learn to use OT for the first time, I tend to see some common issues that can be addressed if the default Preference setting or some OT window property's default was different.

I'm starting this discussion and list with the eventuality of submitting a PR to change the defaults with new users in mind.

I am not looking to create new preferences but modify existing default settings that will mostly affect new users and may affect some existing users if they've never changed that particular setting before.

Suggested changes:

- [ ] Preference: General -> Backup Animation Levels when Saving: Enabled
  - I have another PR that will already change this as well as backup Scenes at the same time
- [ ] Preference: Import/Export -> ffmpeg Timeout: 600
- [ ] Preference: Drawing -> Default Level Type: Toonz Raster Level
  - This will likely be debated, but with the implementation of MyPaint brushes on Toonz Raster levels, I think this might make a better starting experience for new users.
- [ ] Preference: Drawing ->  Autocreation: Use Xsheet as Animation Sheet
  - Suggested because people get confused why all of a sudden a new level is created when drawing
- [ ] Preference: Xsheet -> Cell-dragging Behaviour:  Cells and Column Data
- [ ] Preference: Xsheet -> Show Toolbar in the XSheet: Enabled
- [ ] Preference: Xsheet -> Use Arrow Key to Shift Cell Selecion: Enabled
- [ ] Preference: Animation -> Default Interpolation:  Ease In/Ease Out

Please feel free to suggest any other default preference or window option settings changes you feel will benefit new users.

**Comment by RodneyBaker** [comment]
General thoughts/feedback:
The primary concern I have with Preferences in general is that all should be sticky so that once changed they will remain in that state until changed by the user or overwritten during install (as optional by user during install)

> Preference: General -> Backup Animation Levels when Saving: Enabled
> - another PR that will already change this as well as backup Scenes at the same time

I like the direction here (as outlined in #2514 and can see where having this on by default
I'll add a comment in that PR relating a few concerns about the backup process itself.

>   Preference: Import/Export -> ffmpeg Timeout: 600

I did a quick look to see if there is any downside of having a higher timeout and couldn't find any suggestion that larger timeouts were in any way detrimental.  It is a slight concern however in that I must assume memory is being allocated in some way as to allow for the timeout and if so... an extended timeout would reserve some resources that might otherwise be used elsewhere.  In short, I don't know... so I'm throwing the thought out here for general consideration.  I personally have tended to set ffmpeg timeout to either 120 or 300 (no particular reason for those numbers) and rarely run into timeout problems.  If there is little or no allocation of resources due to the timeout then I see no reason why 600 might not be okay... if no insight can be gained into the process doubling (to 120) or increasing to 300 as a default might also be acceptable.  I suppose a reasonable question might be... why do we desire 600 over some other timeout?


>   Preference: Drawing -> Default Level Type: Toonz Raster Level

I wholeheartedly agree that Toonz Raster should be the default.
Toonz raster is the happy medium between standard raster and vector and it stands to reason it should the focus.

>   Preference: Drawing -> Autocreation: Use Xsheet as Animation Sheet

Agree.  

>   Preference: Xsheet -> Cell-dragging Behaviour: Cells and Column Data

I might have to play with this one but makes sense to me.

>   Preference: Xsheet -> Show Toolbar in the XSheet: Enabled
I don't tend to use the Xsheet Toolbar but it's easy enough to toggle off.
I agree that it'd be a good default to have turned on.

>   Preference: Xsheet -> Use Arrow Key to Shift Cell Selecion: Enabled
Makes sense.

  Preference: Animation -> Default Interpolation: Ease In/Ease Out
I tend to think Linear makes the better default but this is another one that is easy to change.  Ease In/Ease Out is certainly the better default for getting automatic slow in/slow out which tends to improve any rough animation.  I suspect seasoned animators might prefer linear or constant but Ease In/Ease out might be best for use by new users and those with little affinity for Function and Curve Editors.  So... no issue for me with having Ease In/Ease Out.

To reiterate, all this assuming the Preferences get saved and are sticky until intentionally changed as it's one thing to have defaults but quite another to have to constantly reset defaults.

I'll sneak one other minor thought into this post and that is that I'd love to see the Preferences all repeated in an All tab where every Preferences is listed.  This would largely remedy the searching (and forgetting) of where certain Preferences are and what they relate to.

**Comment by manongjohn** [comment]
Preferences changed in the Preference dialog dont change unless changed by the user at least once. Even after upgrade, any preference you touched should remain as you set it. 

A personal preference is saved to file when you change it, even if you change it back. That value is always restored on starting OT. If you dont ever change a preference it is subject to change if the default has changed in the code.

**Comment by gab3d** [comment]
@manongjohn 
First off, I salute all efforts put into making the program easier to new users (also because this often means: easier for everybody else too!).

I agree with all your proposals. There are a couple of them of which I just don't know their impact in most people's worflows, they are:
- **Autocreation: Use Xsheet as Animation Sheet**
I remember when I was starting, I got confused about why the program was creating new levels each time I intended to draw a new frame in the Xsheet. Now I don't really miss it behaving that way. But I fully understand why you're proposing it.
- **Default Interpolation:  Ease In/Ease Out**
I found Bezier to be "more standard" for curve data, but I admit the Ease In/Out type is very easy to control for new users, so I personally have no problem with it being the default.
My real problem with how OpenToonz interpolates movements is that it doesn't generate curved trajectories (but linear ones) between key positions, when the user starts creating keys straight ahead. I think it'd be more useful if it generated a curved trajectory path. 


To add something to what's been proposed, I'd put the Preferences: Tools -> **Use the TLV Savebox to Limit Filling Operations** right into the Brush Tool options bar. Just call it : **Use Savebox** and much more people will start to ask what this function is for (and eventually to actually using it). Where it is now it is condemned to oblivion.

Another option in this category that I'd change its default is, **Dropdown Shortcuts:**. I'd put **Cycle through the available options** as default. As it gives a much faster workflow than to Open the dropdown, and having to click there to select the desired option.

Personally I always use Preferences: Xsheet -> **Sync Level Strip Drawing Number Changes with the Xsheet** activated, but don't know if this impacts negatively in anyone's workflow if activated by default. To me it just makes sense that if I insert a new drawing in the Level Strip, this action doesn't inadvertently change which frames are already exposed in the Xsheet (i.e.  what happens while the option is deactivated).

Also I see as an useful guide the Preferences: Onion Skin -> **Use Onion Skin Colors for Reference Drawings of Shift and Trace**, so perhaps it'd be activated also by default.

Another uselful option that is currently buried inside Preferences and i think users doing quick and dirty pencil tests could benefit a lot from (if they just knew it existed) is Preferences: Interface -> **Show Raster Images Darken Blended**, which allows to overlay several Raster columns using the "Darken" blending mode: no cleanup, no conversion to TLV needed, just throw them in the Xsheet one over the other and test them. I think that one could well be a toggle button in the Viewer's header.

**Comment by artisteacher** [comment]
Since I regularly work with new users, I strongly agree that some preferences need to be changed. 
- backup animation levels = very necessary with the current stability level on macOS
- I actually have my students increase the timeout to 600 when setting up (more due to the convenience of just adding 0’s but a higher number is really important if using OT for stopmotion or etc)
- Toonz Raster does make sense as a default, though I’ve seen some unexpected crashing when drawing with a tablet (once February break is over, I’ll see if I can get more information about that workflow)
- I really like using the Xsheet as Animation sheet, though I like to uncheck the autostretch feature
- I always forget about the cell dragging options, but that sounds like a good idea 
- the toolbar is definitely helpful - if the command bar won’t be added into the room setups, this should probably be enabled 
- I haven’t tried using the arrow keys to change the cell selection, so at this point I don’t have strong feelings either way 
- I also prefer linear interpolation
- shortcuts should definitely be set to toggle through 

I’d also like to see the preference for using the arrow key to add a new frame to the level strip enabled & the compact Xsheet column headers as the default. 

Also, on macOS, we don’t get the option to overwrite our settings or not like you all have in the Windows installer. It would be super helpful...

**Comment by DarrenTAnims** [comment]
I agree with the OPs set of changes, plus...

Personally, I'd like to see a new default level type of "None", so that you can't just start drawing, you have to add a level first, from the menu or toolbar. I think people just draw and never realise what level type they're drawing on and get confused with changing colours changing the drawing or some tools not working. (But I suspect that not many people agree with me on that one)

Not a preference, but on the Interface section, if I change the Unit AND Camera unit to inches or pixels, it doesn't affect New Levels. When I add a new level, it shows the size in mm, which is really difficult to follow. The default camera size is 16" x 9", but the default level size is 406.4mm x 228.6mm. If these were both in inches, when I wanted to double the size of my new level, I could use 32" x 18" more easily than 812.8mm x 456.2mm. Again, not many people use this, but consistency would help.

Interface section, I've reduced my level strip image size to 80x45. This shows twice as many images and for me, works better for that reason.

I've also ticked the Xsheet > Expand Function Editor Header to Match Xsheet Toolbar height. This means I can have the function editor next to the xsheet and the frame numbers line up. This is invaluable when editing keys.

I don't think having an ALL tab would help many of us as the options would still be listed, presumably in the same groupings as on the other tabs. If not, then why not just change them on the other tabs. I've had a look through and I can't really suggest any changes to which tab the options should be on. I think it's just a case of getting used to them.

**Comment by beeheemooth** [comment]
If the width of images in the Level Strip is smaller by default, then the width of the Level Strip window should also be smaller.

**Comment by gab3d** [comment]
@DarrenTAnims 

> Personally, I'd like to see a new **Default Level Type** of "None",

That's called **Autocreation: Disabled**. I agree though, that option should be placed above the **Default Level Type:** option to show the relation between the two in a clearer way.

> Interface section, I've reduced my level strip image size to 80x45. This shows twice as many images and for me, works better for that reason.

I agree with that. A smaller Level Strip show more frames and is thinner, so it allows for a wider Xsheet.

> I've also ticked the Xsheet > **Expand Function Editor Header to Match Xsheet Toolbar Height**.

Also agree. If **Show Toolbar in the Xsheet** is to be activated by default, this one should also be activated too.

**Comment by artisteacher** [comment]
Expanding the function editor is only helpful if you have the Xsheet & function editor next to each other. On a small screen, it really wastes space.

**Comment by artisteacher** [comment]
On a related front, what about turning off some of the Viewer's controls as a default? Or perhaps reorganizing them? Personally, most of the time I only need the playback controls, frame rate, and set key to be enabled. When the viewer is smaller, the playback controls get lost off to the right. This is an issue for small screens but also for larger ones with the Flipbook or etc.

**Comment by gab3d** [comment]
I wonder if it'd be possible to add some kind of modifier key or button in the viewer header to temporarily disable the **Use Xsheet as Animation Sheet**.
I mean, not every time when there is a frame already exposed in the Xsheet and you want to touch it up a little you are in the first frame where its exposure starts. 
So, with the new state of things, I've often found myself drawing a new level frame, when all I intended to do was to add or delete something in the drawing I was seeing (sometimes even related to things happening at that Xsheet frame, but in other columns). 
Because of this, having to either go back to the first exposed cell of that drawing or going to the Preferences to disable the aforementioned option are not comfortable alternatives.

I think that perhaps if the user could hold *Ctrl* key while drawing in the seen frame (or if a *Pin* button existed in the viewer header to let tablet users do the same without a keyboard), this could completely solve that situation.

What do others think about it?

**Comment by RodneyBaker** [comment]
I accidentally posted this to the PR instead of here.
Reposting.

I want to add something here regarding Preference defaults that likely shouldn't be changed but comes up often enough that it should be good to add it for informational purpose here.

When moving from the Cam Stand view to Level Strip new users often wonder where their canvas disappeared to because of the change from white to dark grey. In testing I was trying to find an off white color that was different enough from the canvas to stand out and yet didn't disorient the user as much as the larger shift from white to grey. Setting the RGB colors of the Viewer's background to something like 225, 225, 225 works although will be too bright for most who are staring at the screen all day (perhaps headache inducing even!). As such I'm not recommending a change to the default here so much as adding this note as a reminder that users do have an option to adjust the viewer's background so the transition from Level Strip to Cam Stand view works for them better.

That change can be made via Preferences > Colors > Viewer BG Color
This is the first color setting at the top of the page.

**Comment by gab3d** [comment]
Now that **Show Toolbar in the Xsheet** option is ON by default,
I think **Expand Function Editor Header to Match Xsheet Toolbar Height** should be also ON (that is, if there isn't any serious drawbacks in doing so).

It is useful in rooms where the Xsheet and the Function Editor are placed side by side, because they originally showed the rows at the same level, but now with the Xsheet Toolbar activated by default that is broken.

![imagen](https://user-images.githubusercontent.com/18104091/67147743-eb076c00-f26d-11e9-9885-37350279cdd0.png)

![imagen](https://user-images.githubusercontent.com/18104091/67147780-74b73980-f26e-11e9-9c29-09a01c7f4ee5.png)

**Comment by artisteacher** [comment]
I prefer keeping it off - any unnecessary extra space is really unhelpful for those of us with small screens. If it matters, the default rooms do not have the Xsheet and Function editor placed next to each other.

**Comment by manongjohn** [comment]
Even though that was requested, I purposefully did not enable this by default because none of the current rooms have the Xsheet and Function Editor side by side like that, so I didn't see the point in enabling it because it would needlessly expand the Function editor in existing rooms.

**Comment by turtletooth** [comment]
@manongjohn @artisteacher I agree.

**Comment by gab3d** [comment]
ok, I understand the point. I just find it useful, as this is the Animation room I use:

![imagen](https://user-images.githubusercontent.com/18104091/67227538-cea23580-f40d-11e9-9051-cc998f9b65da.png)

**Comment by manongjohn** [comment]
@gab3d Yeah. For that it makes sense. It might be better to move that setting out of Preferences and make it a button somewhere in the Function Editor to expand the header. The setting can then be saved on a per room basis

**Comment by DarrenTAnims** [comment]
Having a separate button on the actual panel, to me, seems the best idea. But on by default would be my preference too.

**Comment by artisteacher** [comment]
I like the idea of the separate button on the panel too. Still, since there are no cases in the current default rooms where the function editor is next to the Xsheet, I don't think the feature should be on by default. 

What would really be great would be to have the ability to save the button state with a set of rooms. That way, the Ghibli Xsheet room could have the button on by default. The default room collection could keep the off state as the default. When a custom set of rooms is created, the creator could choose to keep it off or on as needed. The best of both worlds!
