### ISSUE TITLE
Known Issues Listing

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#2860]
The purpose of this report is to **collect and document known issues that will likely NOT be resolved with the release of v1.4.**  Most of these issues are tagged as 'Known Issue' for easy reference.

Note:  In many cases the known issue cannot be resolved at present time and therefore workarounds are required.  If the issue is at least known then information on causes, workarounds and potential fixes can be shared.  Some issue may require working with code upstream (such as with issues in the operating system).

**Current Known Issues:**
[LINK](https://github.com/opentoonz/opentoonz/labels/Known%20Issue)
Note that some of these may not be current.  Please feel free to update.

**Comment by RodneyBaker** [comment]
- [ ] opentoonz/opentoonz#7087 "There is no disk in the drive" warning bug (Apr 29, 2018)
- [ ] opentoonz/opentoonz_docs#144 DPI information discarded from various image formats (Apr 27, 2018)
- [ ] opentoonz/opentoonz#1928 Number+Letter Filename Issues (Apr 22, 2018)
- [ ] opentoonz/opentoonz#1327 Shortcut keys: Defaults not compatible with Mac laptops (Jul 12, 2017)
- [ ] opentoonz/opentoonz#1318 Unfilling a space randomly autofills later (Jul 5, 2017)
- [ ] opentoonz/opentoonz#1658 Shortcut keys: Shift [ or { cannot be set  (Dec 6, 2017)
- [ ] opentoonz/opentoonz#2284 Data issue when writing scene file caused failure to load later (Sep 9, 2018)
- [x] opentoonz/opentoonz#242 PNG8 files show glitchy image  (Apr 25, 2016)

**Comment by RodneyBaker** [comment]
Closing as additiions to this topic can be added while closed.

**Comment by RodneyBaker** [comment]
Adding a link to PRs currently on Hiatus as each one identifies some known issue and/or fix:

[Pull Requests currently on Hiatus](https://github.com/opentoonz/opentoonz/pulls?q=is%3Aopen+is%3Apr+label%3AHiatus)

**Comment by RodneyBaker** [comment]
Issues with 'workaround' tag may be the ideal way to address a known issue.

REF:  [Every issue tagged with 'workaround'](https://github.com/opentoonz/opentoonz/labels/workaround)
