### ISSUE TITLE
v1.4 (New Version) General Release

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#2868]
@shun-iwasawa has approved the following general schedule going forward into v1.4:

**Timeframe**
- [x] Mid-December, 2019 - **FEATURE FREEZE**.  New feature PR posted after this will not be included
- [x] Two weeks for bug tracking & translation update
- [x] Beginning of 2020 - Release of v1.4 RC  (done : Jan 17)
- [x] Two+ weeks for urgent bug fix or releasing RC2 (if needed)
- [x] Late January 2020 - Release of v1.4 (done ! : Feb 1)

Comments or suggestions are appreciated.  Thank you!

**Comment by RodneyBaker** [comment]
Checklist (pending)

**Comment by RodneyBaker** [comment]
Change list (WIP)

Completed
- [ ] #2867 Revised vector selection pivot re-centering logic 
- [ ] #2866 Fix customize commands tree structure 
- [ ] #2859 Add "Hide Selected" Command to the Function Editor Spreadsheet 
- [ ] #2858 Enable Animate tool to control precisely by pressing the Alt key 
- [ ] #2855 Fix blank Style Editor panel 
- [ ] #2854 Fix bounding box computation in TXshSimpleLevel 
- [ ] #2848 Modify Maximum Values for Pinch and Magnet Tools Size 
- [ ] #2847 Fix Crash on Launch without Viewer 
- [ ] #2842 Fix pivot location on new/modified vector selections 
- [ ] #2839 Initialize Slider to Linear 
- [ ] #2838 Enable Pencil Mode for Toonz Raster Eraser in Freehand and Polyline types 
- [ ] #2837Selection pivot fix 
- [ ] #2835 Fix Travis macOS builds 
- [ ] #2832 Update Travis to xcode9.2 
- [ ] #2831Fix source comment typos 
- [ ] #2830Enable Geometric Tool for Motion Path 
- [ ] #2829Fix reading escaped double-quotes in quoted strings 
- [ ] #2825 Korean Translations 
- [ ] #2824 Nonlinear Slider for the Brush Size Options 
- [ ] #2823 Fix Main Window Full Screen Mode 
- [ ] #2821Fix lipsync popup layout 
- [ ] #2819 Fix Column Rename Field Position 
- [ ] #2816 New Fx: Corridor Gradient Fx Iwa 
- [ ] #2814 Stop Width Change on Style Editor on Maximize

**Comment by shun-iwasawa** [comment]
@RodneyBaker Thank you for pushing me :-)
Your suggested schedule seems to be reasonable.

**Comment by RodneyBaker** [comment]
Issues that currently have a bounty posted include:

[Link to all issues tagged with 'bounty':  ](https://github.com/opentoonz/opentoonz/labels/Bounty)

**Comment by artisteacher** [comment]
@RodneyBaker Perhaps there should be a pinned issue with open bounties to promote them in a slightly more visible way.

**Comment by RodneyBaker** [comment]
@artisteacher I'll add an issue/report to highlight issue/features on the bounty list but cannot guarantee it will remained pinned.

**Comment by RodneyBaker** [comment]
We should find a way to reward people for their financial support of Opentoonz development.
Even if to only list their names in a special location.

This isn't to suggest that those that don't financially contribute aren't valued also but financially backing developers of Opentoonz is important and contributions are very much appreciated.

Perhaps people and organizations that contribute financially can be listed in the release notes under a special 'additional funding by' header.

**Comment by RodneyBaker** [comment]
This is a note to self to identify features/enhancements that aren't specifically identified via github issue or PR and yet are available to Opentoonz users.

One example of this might be the update to Appveyor automated builds that creates the stuff directory.  A second part of that is how it facilitates creation of portable releases for every new addition to Opentoonz.

Improvements to the installer, documentation, translation (other than those specifically created via PR) should also be identified.

**Comment by RodneyBaker** [comment]
Here's a start of a Release Notes type of listing (still very much a work in progress).
I will minimize the master listing above but try to keep it up to date also.

FEATURES / ENHANCEMENTS 

Highlights
- [ ] Updated/Reorganized Menus
- [ ] New Cache folder Replacement & Clear Cache Command
- [ ] New Camera Column in XSheet
- [ ] New Canon DSLR Camera Capture support
- [ ] New Context Aware Toolbar
- [ ] New Create Blank Drawing command
- [ ] New Fx: Corridor Gradient Fx Iwa 
- [ ] New Fx: Spin Gradient Fx Iwa
- [ ] New Geometry Tool Driven Motion Paths
- [ ] New Guided Drawing/Autoinbetweening
- [ ] New Korean Menu Translation
- [ ] New Level Settings Adjustment for Multiple Selections in XSheet/Timeline
- [ ] New Next/Previous Keyframe Shortcuts
- [ ] New Pencil Mode for Toonz Raster Eraser in Freehand and Polyline
- [ ] New Portable Test Builds via zip file download at Github (Windows Only)
- [ ] New Swap Colors Button for Gradient Fxs 
- [ ] New XDTS File Support (Celsys and Toei Animation xsheet file format Import/Export)
- [ ] ...and much much more.

DRAWING
Guided Drawing/Autoinbetweening
- [ ] #2931 Add Vector Guided Drawing Auto-Inbetween option 
- [ ] #2930 Switch Auto-Inbetween Easing logic 
- [ ] #2935 Fix "Vector Guided Style" preference option 
- [ ] #2686 (WIP) Fix crash when pressing Ctrl+X while moving a line (#2148) 

Color Model / Palettes
- [ ] #2792 Save Specified Frame Numbers of Color Model in Palette 
- [ ] #2787 Fix Color Field Undo Registration 
- [ ] #2700 Fix Color Model fails to display if it is minimized on loading the image 

Level Strip/Filmstrip
- [ ] #2789 Fix filmstrip disabled tools 

XSHEET
Celsys (Clip Studio) and Toei Animation xdts xsheet file format support
- [ ] #2938 XDTS File Support (Import/Export)

Create Blank Frames
- [ ] #2907 Add Create Blank Drawing command 
- [ ] #2936 Fix issues with Create Blank Frames
- [ ] #2739 Fix undo/redo issue when pasting to new frame (#1807)  

Keyframes
- [ ] #2872 Fix navigation keyframe shortcuts skipping
- [ ] #2734 Add next/prev keyframe shortcuts 

Columns / Levels
- [ ] #2884 Fix folded columns slipping
- [ ] #2911 Fix tool crashes on Palette and Zerary column 

Camera Column
- [ ] #2790 Remove selection requirement to toggle Camera Column 
- [ ] #2819 Fix Column Rename Field Position 
- [ ] #2811 Narrow Camera Column
- [ ] #2810 Fix Assertion Failure on Selecting Camera Column
- [ ] #2808 Fix deleted Camera1 returning due to Camera Column refresh  

Note Levels
- [ ] #2897 Allow note frame creation on Animation Sheet 
- [ ] #2915 Recommit Add Note Level context menu 

Drawing Levels
- [ ] #2934 Level Settings for Multiple Selection 
- [ ] #2928 Add Shift Keys commands 

Loading
- [ ] #2924 Allow double-click in Load Scene dialog to open selected scene 
- [ ] #2913 Block reserved file names 
- [ ] #2829 Fix reading escaped double-quotes in quoted strings 

UI/MENUS
Preferences
- [ ] #2894 Overhaul the Preferences 
- [ ] #2921 Fix BG color buttons malfunction 
- [ ] #2918 Quick fix setting undo memory size 
- [ ] #2776 Cache folder replacement & Clear cache command
- [ ] #2866 Fix customize commands tree structure
- [ ] #2685 Modify saving and restoring panels / popups geometries.  

Camera Capture
- [ ] #2698 Add "Always Overwrite" button to Camera Capture 

Full Screen
- [ ] #2823 Fix Main Window Full Screen Mode 

Startup Popup Menu
- [ ] #2875 Enable to create folder in the Startup Popup 

Shortcut Keys
- [ ] #2771 Fix default shortcut assignments 
Toolbars 
- [ ] #2839 Initialize Slider to Linear 
- [ ] #2801 Fix Reset buttons on Tool Option bars 

Guides 
- [ ] #2751 Feature to allow right-click delete of guides 

Lipsync
- [ ] #2821 Fix lipsync popup layout 

Animate Tool
- [ ] #2858 Enable Animate tool to control precisely by pressing the Alt key
- [ ] #2780 Fix Animate Tool Availability 

Selector Tool
- [ ] #2809 Improve vector stroke selection 
- [ ] #2842 Fix pivot location on new/modified vector selections 
- [ ] #2837 Selection pivot fix 
- [ ] #2854 Fix bounding box computation in TXshSimpleLevel 
- [ ] #2867 Revised vector selection pivot re-centering logic 
- [ ] #2804 Improve selection box visibility 

Brush Tool
- [ ] #2824 Nonlinear Slider for the Brush Size Options 
- [ ] #2770 Remember last brush preset used 
- [ ] #2737 Fix crash on centering Toonz Raster brush
- [ ] #2695 Improve deactivate behaviour for brush (#2694)
- [ ] #2687 Put raster brush cursor at center of preview square/circle (#1212)  

MyPaint Brushes
- [ ] #2769 libmypaint DLL update 
- [ ] #2763 Support for MyPaint brush format version 2  
- [ ] #2749 Fix Toonz Raster MyPaint brush center 

Eraser Tool
- [ ] #2838 Enable Pencil Mode for Toonz Raster Eraser in Freehand and Polyline types 
- [ ] #2731 Enable shortcuts for Eraser Tool in Raster Levels (#2724) 

Type Tool
- [ ] #2874 Fix Type Tool Cursor Jumping 
- [ ] #2906 Ignore OT's paste shortcut in TypeTool box 
- [ ] #2773 Fix pasting into Type Tool edit box 

Pump Tool
- [ ] #2805 Fix for pump tool using Wacom tablet (#2180) 

Control Point Editor Tool
- [ ] #2774 Make control points easier to click (#1722) 

Pinch and Magnet Tools
- [ ] #2848 Modify Maximum Values for Pinch and Magnet Tools Size
- [ ] #2699 Fix for changing size of the magnet tool using hotkeys (#1436) 

Style Editor
- [ ] #2882 Scene/Level Editor changes 
- [ ] #2855 Fix blank Style Editor panel 
- [ ] #2892 Fix initial Style Editor palette 
- [ ] #2814 Stop Width Change on Style Editor on Maximize 

Function Editor
- [ ] #2755 Multi Channel Selection in Function Sheet Column Header 
- [ ] #2754 Change Step and Interpolation Type of Selected Multiple Keyframes in Function Editor
- [ ] #2859 Add "Hide Selected" Command to the Function Editor Spreadsheet
- [ ] #2755 Multi Channel Selection in Function Sheet Column Header 
- [ ] #2719 Option to hide inbetween values in the Function Editor spreadsheet 
- [ ] #2717 Revert text align of function editor sheet   

Schematic / FX Editor 
FX
Gradient FX
- [ ] #2816 New Fx: Corridor Gradient Fx Iwa 
- [ ] #2873 New Fx: Spin Gradient Fx Iwa
- [ ] #2786 Add Swap Colors Button to Gradient Fxs 
- [ ] #2878 Linear Gradient Fx Revised
- [ ] #2742 Add "Type" option to gradient fxs  
- [ ] #2891 Fix odd behavior of LinearGradientFx handles 

Bokeh Ref Fx
- [ ] #2743 Fix semi-transparent gap appears with Bokeh Ref Iwa fx 

FX UI/Menus
- [ ] #2925 Add FX Editor to Windows menu 
- [ ] #2799 Add ability to move curve points using arrow keys
- [ ] #2767 Ensure dragged curve handles stay inside graph (#2480)
- [ ] #2711 Fix schematic spline option icon zooming

Schematic 
- [ ] #2802 Fix Crash When Loading MacroFx Containing CurveFx 
- [ ] #2722 Fix crash on loading linked macro fx 
- [ ] #2779 Fix Fx Settings Geometry Restoration 

Motion Paths
- [ ] #2830 Enable Geometric Tool for Motion Path 
 
FILE FORMATS / FFMPEG support
- [ ] #2904 Mark PSD and ffmpeg loaded files as readonly in Level Strip 
- [ ] #2903 Allow Selection Tool copy when level is not editable 
- [ ] #2890 Warn on failing level save during Save All 
- [ ] #2888 Fix file loss issues 
- [ ] #2764 Fix crash on loading Blackmagic codecs 
- [ ] #2880 Handle missing ffmpeg info 
- [ ] #2876 Fix ffmpeg loaded levels 

VIEWERS
- [ ] #2912 (WIP) Fix crash when using keyboard shortcuts while moving a line 
- [ ] #2885 Fix playback skipping first frame 
- [ ] #2883 Fix tool option on Command bar crash 
- [ ] #2847 Fix Crash on Launch without Viewer 
- [ ] #2723 Fix viewer pan disabled on toggling "Compare to Snapshot"

FLIPBOOK
- [ ] #2766 Fix picking color of the snapshot image on Flipbook 
- [ ] #2744 Fix Flipbook Histogram Problems 
- [ ] #2696 Limit flipbook zoom to 100% on initial loading 

CLAPPERBOARD
- [ ] #2510 Fix Audio Sync with Clapperboard

Documentation/Testing
(Not yet implemented) #2919 Update instructions (portablestuff notes) 

BUILD (Github/Installation)
- [ ] #2820 Update README.md 

Enhanced Portable Releases for Testing Builds
- [ ] #2781 Add stuff folder to AppVeyor build artifact 
- [ ] #2756 Use QDir::home() instead of getenv("HOME") in file browser 

Build MacOS
- [ ] #2916 Quick fix for build error 
- [ ] #2900 Fix macOS brew installed glew issue 
- [ ] #2835 Fix Travis macOS builds 
- [ ] #2806 Update macOS Info.plist to include missing strings 

Typos
- [ ] #2831 Fix source comment typos 
- [ ] #2740 Fix misc. source comment and doxygen typos in ./toonz/sources/toonzlib 

Translations
- [ ] #2825 Korean Translations 
- [ ] #2761 Add English Fx Help files 
- [ ] #2720 Translation fixes and Japanese translation update 

Command Line/Scripting
- [ ] #2750 Enable system path arguments in tcomposer 

LINUX
- [ ] #2735 Add Desktop and Documents location in file browser for Linux 
- [ ] #2690 Update how_to_build_linux.md  Build / Install Linux
 
MISC
- [ ] #2697 Fix crash with visualization commands 
- [ ] #2688 remove tArrayCount macro  
- [ ] #2714 Fix crash on activating cycle 

Much more yet to be added...

**Comment by gab3d** [comment]
>  #2761 Add English Fx Help files

I will also add Spanish FX Help files.
...now in progress, due before the end of the year.

**Comment by shun-iwasawa** [comment]
It's about time to freeze features for v1.4 .
To contributors, please let me know here if you have any WIP features which is not yet posted in PR but you really want to put in the next version. Thanks!

**Comment by RodneyBaker** [comment]
@shun-iwasawa @gab3d recently conveyed he would like to assist another contributor/developer with getting  #2939 into v1.4.  Perhaps he can comment and clarify why it should be added now versus wait.

If there are landing pages in Opentoonz documentation (presumably built by @gab3d), the two Help menu links (Support Opentoonz and Report Bug) are a highly desired addition.

**Comment by RodneyBaker** [comment]
Happy New Year!
While we are still a few days away from a Release Candidate We are at the point where a call for documentation of v1.4 appears appropriate.

As we test current nightly releases and the (pending) Release Candidate please consider recording, documenting and sharing that experience.  Goals of this effort include:

- [ ] Test and Report
- [ ] Demonstrate intended workflow
- [ ] Explore alternative uses
- [ ] Identify critical issues
- [ ] Document variables and constraints
- [ ] Capture the experience
- [ ] Share results

Ideal locations for feedback are the PR and/or referenced issues and links to videos, sample files and additional information are always appreciated. 

Format
While we do not currently have a template for demonstrations/walkthroughs @shun-iwasawa does have examples of several feature demonstrations on youtube:  [Link](https://www.youtube.com/watch?v=O9JnYWtP5Ro)

Thanks!

**Comment by RodneyBaker** [comment]
While not strictly speaking 'Opentoonz' a mention of updates to **GTS** and the introduction of **Kumoworks** is in order as well as they have been part of 2019 development.

**Comment by beeheemooth** [comment]
My finger gets tired when I scroll through this schedule. ^_^

**Comment by shun-iwasawa** [comment]
I'll start working for releasing (belated) v1.4RC once #3029 is reviewed & merged.

@RodneyBaker 
Can I use your [previous post](https://github.com/opentoonz/opentoonz/issues/2868#issuecomment-565682451) for the release note? Thanks!

**Comment by RodneyBaker** [comment]
@shun-iwasawa  Most definitely.  Please do.

**Comment by shun-iwasawa** [comment]
I just released V1.4RC . Thank you!

**Comment by RodneyBaker** [comment]
Quite a number of additional fixes to various issues have been added since the v1.4 Release Candidate went public.  Here is a rough cut of those as of this moment:

- [x] #3073 Fix guided drawing issues 
- [x] #3071 Fix CurveFx Crash 
- [x] #3065 Fix Crash on Exporting XDTS When There are No Columns to be Exported 
- [x] #3064 Modify Creating Scene from Startup Popup 
- [x] #3063 Fix Translation for Toonz Vector Brush Tool 
- [x] #3060 Instructions on how to compile stylesheet qss files on Linux 
- [x] #3058 Revert "None" line pocessing option to the cleanup settings 
- [x] #3054 Fix Load Folder crashing while loading tga files 
- [x] #3053 Revert Delete Unused Styles right-click command 
- [x] #3050 Russian Translation Updates 
- [x] #3048 FX help files - new ones + fixes + Spanish version by gab3d 
- [x] #3046 Fix Window Activating Behavior 
- [x] #3037 Fix incorrect Function Editor Easing labels 
- [x] #3033 Fix Export XDTS Command Missing in Menubar

**Comment by shun-iwasawa** [comment]
I'm planning to release the v1.4 in a couple of days or so.
Please let me know if anyone is working on a bug fix which is not yet posted in PR. Thanks!

**Comment by manongjohn** [comment]
FYI, I was just given some Korean translation corrections to submit.

**Comment by shun-iwasawa** [comment]
@manongjohn 

> FYI, I was just given some Korean translation corrections to submit.

I'm sorry to say but the fix may not be included in v1.4. I'm thinking of releasing it tonight (now it's 4pm in Japan).

**Comment by shun-iwasawa** [comment]
I just released V1.4 . Please let me know if there are any problems with it. Thanks!

**Comment by manongjohn** [comment]
> @manongjohn
> 
> > FYI, I was just given some Korean translation corrections to submit.
> 
> I'm sorry to say but the fix may not be included in v1.4. I'm thinking of releasing it tonight (now it's 4pm in Japan).

That's unfortunate for the Korean translations. The brush tool option bar is not going to be translated properly. While working on prepping the new translations I was given, i noticed the brush options translations were lost, likely due to the issue you found so they were not there when I built the files.

**Comment by shun-iwasawa** [comment]
@manongjohn OK I'll try to fix it and silently replace the installer if possible.
@RodneyBaker Can you please wait to merge any PRs? Thanks.

**Comment by shun-iwasawa** [comment]
Thank you @manongjohn for posting the fix. Now let's wait for the installers to be built.

**Comment by manongjohn** [comment]
Thanks.  That would be great if you can.  I would have had it before you released but I had a question for him and he didn't get the answer til about an hour ago. :(

**Comment by shun-iwasawa** [comment]
Oops, now I realize that the same problems occur in Japanese translations!

**Comment by manongjohn** [comment]
Spanish and Czech translations also impacted.

**Comment by shun-iwasawa** [comment]
I'll check and modify all languages right away.

**Comment by shun-iwasawa** [comment]
Replacement done :+1:

**Comment by manongjohn** [comment]
Thanks for fixing!

**Comment by RodneyBaker** [comment]
Congratulations to all involved in the release of v1.4!

CLOSING!  :)

**Comment by FerrLui** [comment]
Thank You!!!!!! This is a great job. AGAIN, thank You very much.

пт, 17 янв. 2020 г., 6:13 AM shun-iwasawa <notifications@github.com>:
