### ISSUE TITLE
Status Check:  Mypaint Brushes

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#2927]
This is a review of various MyPaint updates that will and will not get included in the v1.4 release.

MyPaint updates merged since v1.3 that will be in v1.4 include:
- [x] #2768 MyPaint libmypaint 1.4,0 Released
- [x] #2763 Support for MyPaint brush format version 2
- [x] #2769 libmypaint DLL update 
These update Mypaint DLL for windows to Mypaint v1.4, resolve a crash and allow use of older MyPaint brush packs.

Note that none of those other older brush packs are currently included in v1.4
There are potentially several hundred brushes that could be added to Opentoonz. 

**Question:**  Is it advisable that we add more MyPaint brushes before improving brush management?

One suggested brush set for newer brushes was previously identified here:  
- [ ] #2014 Add 'Good Pack' MyPaint brush pack
This didn't get included in the v1.3 release and there may be some issues preventing inclusion.

Over All Status:
- [x] Update Mypaint DLL
- [x] Resolve conflict/crash caused by presence of Mypaint installation
- [ ] Describe Opentoonz internal brush management options and shortfalls
- [ ] Describe external brush management options (operating system, MyPaint, etc.)
- [ ] Identify/Add additional old brush sets (early version of brushes)
- [ ] Identify/Add additional new brush sets (standard version of brushes)
- [ ] Identify/Add advanced capabilities of MyPaint Brushes (Note:  Not anticipated in near future)
- [ ] Review and document current MyPaint features in Opentoonz
- [ ] Identify differences (advantages/disadvantages) of MyPaint brush via comparison of raster and Toonz raster level capability/workflow.

_This listing does not suggest these line items should be implemented but rather lists them for review purposes._

It would be ideal to determine by 15 December what if any MyPaint changes are desired for inclusion in v1.4 release.  This will then set the stage for MyPaint development in 2020 and beyond.

**Comment by RodneyBaker** [comment]
In the Opentoonz Forum there are several topics to include Feature Requests related to Opentoonz:
- [ ] Feature Request:  Allow Shortcut for MyPaint Brushes/Eraser ([LINK](https://groups.google.com/forum/#!searchin/opentoonz_en/mypaint%7Csort:date/opentoonz_en/dGtEPP-_6qo/g89O090QAgAJ))

**Comment by RodneyBaker** [comment]
The following is a historical review of mypaint related issues/PRs:

#2927 (WIP) Status Check: Mypaint Updates for v1.4 Question
#2876 Fix ffmpeg loaded levels 
#2868 v1.4 (New Version) General Release Schedule
#2846 (Discussion) New Level buttons 
#2824 Nonlinear Slider for the Brush Size Options 
#2803 Style Editor panels remember selected tab. 
#2768 MyPaint libmypaint 1.4.0 released recently
#2763 Support for MyPaint brush format version 2 
#2749 Fix Toonz Raster MyPaint brush center 
#2747 Do you provide installer for Linux?
#2746 [Discussion] OpenToonz development Roadmap
#2732 Crash when select the Brush Tool.
#2701 cannot build libmypaint dependency on Fedora. Build / Install Linux
#2656 (WIP) Krita-Like Assistant Tool 
#2630 Opentoonz crashes whenever I click on the raster brushes option
#2614 Fix "Convert to Vectors" command for TLV with MyPaint Styles 
#2602 Raster brush overlapping issue
#2591 Lines often don't draw on MacOS 10.14.3 and 10.14.4 MacOS
#2575 Add shortcuts for MyPaint Brush toolbar options 
#2523 Discussion: Updating default preferences for new users
#2517 Fix Toonz Raster brush style (crash)
#2516 Crash loading palette into Toonz Raster (crash)
#2482 Brush size is initially shown incorrectly for MyPaint styles
#2479 Fx setting popup enhancements 
v1.3 (New Version) Release Schedule

**Comment by artisteacher** [comment]
> Question: Is it advisable that we add more MyPaint brushes before improving brush management?

As it is there are already too many MyPaint brushes to keep track of easily. I vote for better brush management first.

**Comment by RodneyBaker** [comment]
Consensus is that adding new brushes should wait until 2020 development cycle where additional management and organizational tools can be developed.

See you all in 2020 for the next phase of MyPaint brushes in Opentoonz!

**Comment by RodneyBaker** [comment]
Reopening in light of potential for porting of Brush management (port from Tahoma2D) as well as adding brushes (where applicable.

The main reason we decided not to add more brushes was because Opentoonz had no easy way to organize those brushes.  A working brush management system with ability to Favorite and create custom directories for brushes can be seen in current releases of Tahoma2D.  REF:  https://github.com/tahoma2d/tahoma2d/pull/789

**Comment by artisteacher** [comment]
The brush organization in T2D is super helpful and works well. It's definitely worth adding to OT if someone is able/willing to port it.

**Comment by RodneyBaker** [comment]
Consideration for adding these additional brushes is now back on the table due to implementation of #4572.
