### ISSUE TITLE
Status Check:  Filenaming issues

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#2950]
This is a review of Filenaming issues in Opentoonz.
At present a general inventory of related issues both open/closed include:

- [ ] #2945 Levels with two character alpha numeric filename fail Bug Enhancement by mosujiba
- [x] #2908 AUX.pli Windows error. Bug Known Issue by papio-pl
- [x] #2537 Filenaming:  Invalid File Extension Warning
- [x] #967 Filenaming: Sequence can start in 0 not only 1 
- [x] #2829 Fix reading escaped double-quotes in quoted strings by manongjohn 
- [x] #2827 Quotations in level name result in empty scene on open  by artisteacher
- [x] #2712 Save previewed frames - can't choose file format by gab3d 
- [x] #2607 Allow sequenced files starting with 0 by manongjohn (Fixes #967)
- [x] #2306 Importing an image renames it incorrectly by DarrenTAnims 
- [ ] #2231 Filenaming error with SVG sequence import 
- [x] #2209 Cannot load images with simple numerical names by RodneyBaker 
- [x] #2143 Set System Paths with Command Line Qualifiers 
- [x] #2117 Levels lost: 0 byte files created when Projects Settings append options on (?)
- [ ] #2094 Filenaming: Storyplanner png "malformed frame name" error by matitanimata
- [x] #1996 Filenaming: wav files with progressive numeration by matitanimata 
- [ ] #1928 Number+ Letter Filename Issues
- [ ] Symlink loading issues 

Closing for the present.
