### ISSUE TITLE
Status Check:  Shortcut Key Issues

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#2971]
There are a number of issues relating to shortcut keys that are known and most if not all have workarounds.  It will be good to track these and determine how best to resolve the various conflicts and/or document as known issues so users can determine best options if/when encountering them.

- [ ] Shortcuts such as the letter z cannot be used in Notelevels (and with TextFX).  'Set Keyframe' is currently assigned the letter z to facilitate studio workflow in the xsheet. (Status:  Various workarounds)

- [x] Shortcuts cannot be defined directly via Number Pad but... once assigned the Numberpad can be used for shortcuts.  Ref:  #684  (Status:  Adequate workaround)

- [ ] Some keys and key combinations cannot be used as shortcuts. Ref:  #1658 (and others)

- [ ] Operating system shortcuts may conflict with application shortcuts.

- [ ] Request to reorganize Shortcuts dialogue.  REF:  #415

- [x] Adding default keyboard shortcuts + Enable to delete default shortcuts REF:  #236

Others:  #2899, #2906, #679

---
TO DO
---
Determine best practices and approaches to resolve issues with shortcut key assignments while optimizing workflow for production.
