### ISSUE TITLE
v1.6 Release Schedule

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#4081]
v1.6 Release Schedule  

- [x] Feature Freeze (15 February) 
- [x] Two weeks for bug tracking and translations
- [x] Release Candidate
- [x] Two weeks for urgent bug fix (as required) - releasing RC2 (as needed)
- [x] Full Release

**Comment by RodneyBaker** [comment]
Placeholder

**Comment by RodneyBaker** [comment]
Placeholder

**Comment by RodneyBaker** [comment]
Placeholder

**Comment by RodneyBaker** [comment]
Placeholder

**Comment by RodneyBaker** [comment]
Placeholder

**Comment by RodneyBaker** [comment]
Placeholder

**Comment by RodneyBaker** [comment]
(early draft change log)

Viewers/Flipbook
#4093 30 bit display feature by shun-iwasawa
#4202 Fix Flipbook wobbling when dragging while playing by shun-iwasawa 
#4197 Enhance Flipbook playback by shun-iwasawa
#4108 Modify Flipbook Histogram by shun-iwasawa
#4105 Fix crush on showing snapshot in flipbook by shun-iwasawa

Xsheet / Timeline
#4194Fix pressing Shift key loses focus when renaming cell by shun-iwasawa
#4178 Cell Mark feature by shun-iwasawa
#4050 Fix Autorenumber of Raster Level by shun-iwasawa
#4124 Xsheet Minimum Layout by shun-iwasawa
#4141 Fix undo pasting raster selection to cell by shun-iwasawa
#4134 Tahoma2D porting: Allow Changing Parent of Column from XSheet by jeremybullock ported by shun-iwasawa
#3944 Xsheet Zoom Control by shun-iwasawa 
#3922 Fix Cell Selection on Click by shun-iwasawa 

Rendering / Image formats 
#4205 Multi-Thread FFMPEG and responsive finalizing window by justburner

Image formats
#4192 OpenEXR I/O by shun-iwasawa
#4082 Add Raster Lock Alpha tool setting by manongjohn 
#4167 Fix PSD loading and level format preferences by shun-iwasawa
#3897 Fix PSD Loading by shun-iwasawa

Notelevels
#4190 Note level column enhancement by shun-iwasawa

Level Strip 
#4186 Fix FrameIds Inconsistency in Level Strip Commands by shun-iwasawa
 
Export
#4185 Fix TVP JSON export by shun-iwasawa 
#4203 Modify Export Xsheet PDF feature by shun-iwasawa
#4196 Xsheet PDF Export: Tickmark breaks continuous line by shun-iwasawa
#4020 TVPaint JSON export (Experimental feature) by shun-iwasawa 

File Browser
#4183 Enable To View Palette Files From the File Browser by shun-iwasawa
#4095 Fix "Show Folder Contents" command for UNC path by shun-iwasawa 

Cleanup
#4182 Enable to Cleanup Without Line Processing by shun-iwasawa

Effects/Schematic
#4163 Fix crash on creating Macro Fx from the Fx Browser by shun-iwasawa
#4176 Allow Renaming Pass Through Nodes by konero
#4077 Fix Fx intensity malfunction by shun-iwasawa 
#4075 Fix Fx placement  by shun-iwasawa 
#4068 Fix PN Clouds Ino Fx by shun-iwasawa 
#4066 Fix channel clamping behavior in Layer Blending Fxs by shun-iwasawa 
#4032 Change behavior of the Layer Blending Ino fxs when the background layer does not exist  by shun-iwasawa 
#3993 Bokeh Advanced Fx Quick Fix by shun-iwasawa 
#3991 New Fx: Bokeh Advanced Iwa (and Bokeh Fxs overhaul) by shun-iwasawa 
#3969 Fix and refactor Line Blur Fx Ino by shun-iwasawa 
#3955 Add the Linear color space option to all other Layer Blending Ino fxs by shun-iwasawa
#3914 Particles Fx : Use 16bpc Control Image for Gradient by shun-iwasawa 
#3905 Raylit Fx Enhancement by shun-iwasawa 
#4172 Fix Zerary Fx bugs by shun-iwasawa
#4169 Fix FxId and expression handling by shun-iwasawa 
#4146 Add New Shader Fx: HSL Blend GPU by justburner
#4059 Fix Fx Gadget Offset by shun-iwasawa
#4048 Fix Bokeh Fxs Artifacts by shun-iwasawa
#4055 Add Fx Global Controls by shun-iwasawa
#4036 Redesign the Pass Through Fx Node by shun-iwasawa
#4100 Fix Friction parameter behavior of the Particles Fx by shun-iwasawa
#4098 Fix Rendering Fx After Xsheet Node by shun-iwasawa 
#4094 Fix Crush On Inserting Fx by shun-iwasawa
#4025 Fx schematic node placement fix by shun-iwasawa 
#4089 Fix Spectrum by shun-iwasawa

Shortcuts
#4175 Fix shortcut loading from file by shun-iwasawa
#4003 Fix crash on clicking shortcut tree by shun-iwasawa 
#3930 Fix Shortcut Input by shun-iwasawa 
#3927 Fix tool options' shortcuts to work without opening tool options bar by shun-iwasawa 

Audio
#4164 Improvements to Audio Recording by justburner

File I/O
#4160 File Path Processing Using Regular Expression by shun-iwasawa

Xsheet (Export)
#4057 Export Xsheet to PDF by shun-iwasawa
#4073 Fix Export Xsheet PDF by shun-iwasawa
#4071 Export Xsheet PDF feature modification by shun-iwasawa 

Mypaint Brushes
#4042 Fix margin bottom slider-v-handle by andeon
#4039 Fix brushes marker and hatch (Raster Brushes) by andeon

Camera Capture
#4037 Enable Inputting Frame with Suffix in Camera Capture by shun-iwasawa
#3951 Fix camera capture's level control by shun-iwasawa 
#3945 Camera capture : Connect to any camera on start by shun-iwasawa 

Control Point Editor Tool
#4109 Fix crash on deleting control point while dragging  by shun-iwasawa

Plastic Tool
#3947 Fix mesh file naming by shun-iwasawa 

UI
#4195 Project Settings-aware Frame Number Field Width by shun-iwasawa
#4132 Fix wheel scrolling on the output settings popup by shun-iwasawa
  #4030 Fix text color style inside some windows by andeon  by shun-iwasawa 
  #4021 Fix text color style inside some windows by andeon 
#3898 Fix Missing Checkboxes in Menu Item by shun-iwasawa 

Conversion
#4120 Fix Convert to TLV Palette Saving  by shun-iwasawa

UNDO
#4087 Fix Undo Malfunction by shun-iwasawa

#4004 Fix Paste Color command not to set the "edited flag" to normal styles by shun-iwasawa 
#4001 Update Appveyor OpenCV Version by shun-iwasawa

#3990 Change the Paste Color command behavior not to overwrite link information by shun-iwasawa
#3989 Enable to Paste Style's Color Into Color Field by shun-iwasawa 
#3988 Compass Gadget for Radial and Spin Blur Fxs by shun-iwasawa 
#3974 Modify sync scroll between Xsheet and Function editor panels by shun-iwasawa 

Build Environment
#4049 Actions: update windows runner by shun-iwasawa
#4046 Backlog of PR #4037, fix for 32bit build by shun-iwasawa
#4179 update appveyor opencv version to 4.5.4 by shun-iwasawa
#4187 Fix build with clang 13: no member named 'copy' in namespace 'std' by rozhuk-im

Github Actions
#3971 Actions: update scripts by shun-iwasawa 
#3899 Actions: Use Custom Qt for Windows Build by shun-iwasawa
#4023 Actions: Update Windows Runner by shun-iwasawa 

Typos
#4002 Fix source typos by luzpaz 
#4000 fix various typos by luzpaz 

#3917 Fix Raster Deformation Slowness by shun-iwasawa 
#3910 Fix Memo Popup Background Color by shun-iwasawa 
#3895 Fix Brush Smoothing by shun-iwasawa

**Comment by shun-iwasawa** [comment]
Thank you @RodneyBaker for continuous help and for preparing the schedule of next release.

I think I'll freeze the features for v1.6 and start 2-week bug tracking and translations period.
Will release 1.6RC at the end of this month. 

@rabe01 
The feature for changing the pinned center seems to be intentionally removed by [this PR](https://github.com/opentoonz/opentoonz/pull/3275) . Can you please advise if it can be simply reverted, or it would be better to make this operation needs some modifier key, like ctrl+click in order to prevent mishandling?

**Comment by gab3d** [comment]
@shun-iwasawa thanks!
I'd really like the Pinned Center functionality to be restored, if possible.
If it causes certain problems, perhaps a good tutorial on how to safely use it could make users aware of its potential and the best ways to use it.

**Comment by rabe01** [comment]
I don't want to say anything wrong about that. I only played with the older version (1.4) for a very short time.
Here's an example (I used an "extra-shape" to have a pivot point for the whole leg - a "hip joint").
I was able to lift the foot, bend the leg, to rotate the foot I used a Temporarily Pinned Center - 3rd frame, then skeleton pinned center to the foot and leg straight.
![ik2](https://user-images.githubusercontent.com/33298695/154163784-41a952e5-9389-405c-940b-aab813a59fbd.png)

I miss this option to fix the center arbitrarily in the current version. It seems correct that setting the skeleton pinned center per click can lead to errors.
I don't know enough about the many problems that others have described here.
I would just wish for an effective IK.

- I found it a bit tricky to select the individual shapes in IK mode.

- Also, I could imagine that an easier switch from IK to Forward Kinematic would be cool.

- I haven't found a way to select columns/levels in the canvas.

**Comment by RodneyBaker** [comment]
I'm hoping we get @psychoanima to add his thoughts related to IK and pinne center.
REF:  #2368

**Comment by RodneyBaker** [comment]
@shun-iwasawa If it's not too late I have heard from @justburner of his desire to push one more PR forward to get it into v1.6.
I'll let him comment on that.  I'm posting this to make sure we at least have it on the radar.

**Comment by gab3d** [comment]
@RodneyBaker 
I've just redone the @psychoanima example scene in #2368 with my recently installed Toonz 7.1, and sadly I must confirm Toonz has exactly the same behavior shown in his video. 😞 
It's not that the feature should not be restored to be used at user's own risk, but there's obviously problems in how it was working in Toonz already, which implies there's no good code to take as guide to make it work well.

**Comment by RodneyBaker** [comment]
Thanks @gab3d for diving in and testing
A question this raises though is if we can restore at least the capbility to shift pinned center so that process can at least work.
About a week ago I played with IK and it worked... and I figured out approaches for working around things that didn't appear to work at first... but I must confess I don't know enough about how it *should* work to reliably offer suggestions.  Most of my encounters with FK/IK in 3D are based on processes that I didn't give much thought to with regard to the deeper processes behind it all.

I do note the vast majority of Jeremy's changes in #3275 are translation (from Italian to English) and adding additional commentary.  The actual change of code in that PR is minimal.  There is also the somewhat humorous removal of the term 'IhateIK' which might suggest why we are where we are currently with the code.

All this to suggest that we mostly need to make a decision to leave the processes in place as they are now or revert that part of the code where actual changes to code occur... either way with the idea that IK workflow would be considered for additional changes in the future.

**Comment by gab3d** [comment]
Shift+click (Temporary Pinned Center) is working right now.
What was concealed was the Pinned Center (click) functionality, Shun proposed to bring it back, but using Ctrl+click, which to me makes sense, since at least we avoid users to use it without explicit intention.

I think we should make an effort to recruit some developer which is versed in bones, IK, etc. to help make this part of the program improve.

**Comment by RodneyBaker** [comment]
@shun-iwasawa  Are there translation files that need to go out for those working on their respective translations?

The only files I am aware of for translation are here:  https://github.com/opentoonz/opentoonz/tree/master/toonz/sources/translations

**Comment by RodneyBaker** [comment]
For those looking in...
We are currently in the 2 week period prior to release candidate where focus is on bugs... especially any showstopping bugs... and translations.

Here's the list of current bugs, some of which also have a crash label:  https://github.com/opentoonz/opentoonz/issues?q=is%3Aopen+is%3Aissue+label%3Abug

**Comment by RodneyBaker** [comment]
Current crash list:  https://github.com/opentoonz/opentoonz/issues?q=is%3Aopen+is%3Aissue+label%3Acrash

**Comment by RodneyBaker** [comment]
All,
This mostly concerns closing the loop for current reports going into release of v1.6 and giving each report maximum focus moving foward.

In order to work through and organize the backlog of reports (both open and closed) the plan is to add a 'resolved' label.
This might be controversial as that is generally what the closed label accounts for right?

The underlying issue is that not all closed issues have been resolved.
Many reports of the past were closed when it was standing policy that any report that smelled like a feature request was closed with (ideally) a referral to the opentoonz google user forum.  This is no longer applicable.

Moving forward we can look hard at revising the current labeling to reduce and eleminate redundancy.
We may even be able to remove this new fangled resolved label at the point where more clarity is evident in closures.

The end goal is to resolve user concerns as identified in their respective reports.
My primary and personal consideration in labeling a report closed is the reporter's satisfaction.  
If they are satisified then the report is resolved.

There may be other and better options.
As always I appreciate your feedback on how we can improve this process especially as we head toward v1.7 and beyond.

For reference here is the default labels that github repos come with:
<html>
<body>


Label | Description
-- | --
bug | Indicates an unexpected problem or unintended behavior
documentation | Indicates a need for improvements or additions to documentation
duplicate | Indicates similar issues, pull requests, or discussions
enhancement | Indicates new feature requests
good first issue | Indicates a good issue for first-time contributors
help wanted | Indicates that a maintainer wants help on an issue or pull request
invalid | Indicates that an issue, pull request, or discussion is no longer relevant
question | Indicates that an issue, pull request, or discussion needs more information
wontfix | Indicates that work won't continue on an issue, pull request, or discussion


</body>
</html>

Several of these miss the mark for our current approach to Opentoonz development but I do consider them a reasonable default.

**Comment by RodneyBaker** [comment]
Perhaps to late for this v1.6 release but I see some news related to Qt and opensource (bug fixes):

https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.3/release-note.md

**Comment by shun-iwasawa** [comment]
I've just released V1.6RC. Thank you!

**Comment by RodneyBaker** [comment]
Posting a master listing for purpose of scrubbing:

- [ ] #3895 Fix Brush Smoothing by shun-iwasawa
- [ ] #3897 Fix PSD Loading by shun-iwasawa
- [ ] #3898 Fix Missing Checkboxes in Menu Item by shun-iwasawa
- [ ] #3899 Actions: Use Custom Qt for Windows Build by shun-iwasawa
- [ ] #3905 (enhanced) Raylit Fx by shun-iwasawa
- [ ] #3910 Fix Memo Popup Background Color by shun-iwasawa
- [ ] #3914 (enhanced) Particles Fx : Use 16bpc Control Image for Gradient by shun-iwasawa
- [ ] #3917 Fix Raster Deformation Slowness by shun-iwasawa
- [ ] #3922 Fix Cell Selection on Click by shun-iwasawa
- [ ] #3927 Fix tool options' shortcuts to work without opening tool options bar by shun-iwasawa
- [ ] #3930 Fix Shortcut Input by shun-iwasawa
- [ ] #3944 (new) Xsheet Zoom Control by shun-iwasawa
- [ ] #3945 Camera capture : Connect to any camera on start by shun-iwasawa
- [ ] #3947 Fix mesh file naming by shun-iwasawa
- [ ] #3951 Fix camera capture's level control by shun-iwasawa
- [ ] #3955 Add the Linear color space option to all other Layer Blending Ino fxs by shun-iwasawa
- [ ] #3969 Fix and refactor Line Blur Fx Ino by shun-iwasawa
- [ ] #3971 Actions: update scripts by shun-iwasawa
- [ ] #3974 Modify sync scroll between Xsheet and Function editor panels by shun-iwasawa
- [ ] #3988 (new) Compass Gadget for Radial and Spin Blur Fxs by shun-iwasawa
- [ ] #3989 (new) Enable to Paste Style's Color Into Color Field by shun-iwasawa
- [ ] #3990 Change the Paste Color command behavior not to overwrite link information by shun-iwasawa
- [ ] #3991 (new) Bokeh Advanced Iwa Fx(and Bokeh Fxs overhaul) by shun-iwasawa
- [ ] #3993 Bokeh Advanced Fx Quick Fix by shun-iwasawa
- [ ] #4000 fix various typos by luzpaz
- [ ] #4001 Update Appveyor OpenCV Version by shun-iwasawa
- [ ] #4001 Update Appveyor OpenCV Version by shun-iwasawa
- [ ] #4002 Fix source typos by luzpaz
- [ ] #4003 Fix crash on clicking shortcut tree by shun-iwasawa
- [ ] #4004 Fix Paste Color command not to set the "edited flag" to normal styles by shun-iwasawa
- [ ] #4020 (new) TVPaint JSON export (Experimental feature) by shun-iwasawa
- [ ] #4021 Fix text color style inside some windows by andeon
- [ ] #4023 Actions: Update Windows Runner by shun-iwasawa
- [ ] #4025 Fx schematic node placement fix by shun-iwasawa
- [ ] #4032 Change behavior of the Layer Blending Ino fxs when the background layer does not exist by shun-iwasawa
- [ ] #4036 Redesigned Pass Through Fx Node by shun-iwasawa
- [ ] #4037 Enable Inputting Frame with Suffix in Camera Capture by shun-iwasawa
- [ ] #4039 Fix brushes marker and hatch (Raster Brushes) by andeon
- [ ] #4042 Fix margin bottom slider-v-handle by andeon
- [ ] #4046 Backlog of PR - [ ] #4037, fix for 32bit build by shun-iwasawa
- [ ] #4048 Fix Bokeh Fxs Artifacts by shun-iwasawa
- [ ] #4049 Actions: update windows runner by shun-iwasawa
- [ ] #4050 Fix Autorenumber of Raster Level by shun-iwasawa
- [ ] #4055 Add Fx Global Controls by shun-iwasawa
- [ ] #4057 (new) Export Xsheet to PDF by shun-iwasawa
- [ ] #4059 Fix Fx Gadget Offset by shun-iwasawa
- [ ] #4066 Fix channel clamping behavior in Layer Blending Fxs by shun-iwasawa
- [ ] #4068 Fix PN Clouds Ino Fx by shun-iwasawa
- [ ] #4071 Export Xsheet PDF feature modification by shun-iwasawa
- [ ] #4072 Typos found by alexmyczko (assist by luzpaz)
- [ ] #4073 Fix Export Xsheet PDF by shun-iwasawa
- [ ] #4075 Fix Fx placement by shun-iwasawa
- [ ] #4077 Fix Fx intensity malfunction by shun-iwasawa
- [ ] #4082 (new) Add Raster Lock Alpha tool setting by manongjohn
- [ ] #4087 Fix Undo Malfunction by shun-iwasawa
- [ ] #4089 Fix Spectrum by shun-iwasawa
- [ ] #4093 (new) 30 bit display feature by shun-iwasawa
- [ ] #4094 Fix Crush On Inserting Fx by shun-iwasawa
- [ ] #4095 Fix "Show Folder Contents" command for UNC path by shun-iwasawa
- [ ] #4098 Fix Rendering Fx After Xsheet Node by shun-iwasawa
- [ ] #4100 Fix Friction parameter behavior of the Particles Fx by shun-iwasawa
- [ ] #4105 Fixed crash on showing snapshot in flipbook by shun-iwasawa
- [ ] #4108 Modified Flipbook Histogram by shun-iwasawa
- [ ] #4109 Fix crash on deleting control point while dragging by shun-iwasawa
- [ ] #4120 Fix Convert to TLV Palette Saving by shun-iwasawa
- [ ] #4124 (new) Xsheet Minimum Layout by shun-iwasawa
- [ ] #4132 Fix wheel scrolling on the output settings popup by shun-iwasawa
- [ ] #4134 Tahoma2D port: Allow Changing Parent of Column from XSheet by jeremybullock ported by shun-iwasawa
- [ ] #4141 Fix undo pasting raster selection to cell by shun-iwasawa
- [ ] #4146 (new) Shader Fx: HSL Blend GPU by justburner
- [ ] #4160 File Path Processing Using Regular Expression by shun-iwasawa
- [ ] #4163 Fix crash on creating Macro Fx from the Fx Browser by shun-iwasawa
- [ ] #4164 Improvements to Audio Recording by justburner
- [ ] #4167 Fix PSD loading and level format preferences by shun-iwasawa
- [ ] #4169 Fix FxId and expression handling by shun-iwasawa
- [ ] #4172 Fix Zerary Fx bugs by shun-iwasawa
- [ ] #4175 Fix shortcut loading from file by shun-iwasawa
- [ ] #4176 Allow Renaming Pass Through Nodes by konero
- [ ] #4178 (new) Cell Mark feature by shun-iwasawa
- [ ] #4179 update appveyor opencv version to 4.5.4 by shun-iwasawa
- [ ] #4182 Enable to Cleanup Without Line Processing by shun-iwasawa
- [ ] #4183 Enable To View Palette Files From the File Browser by shun-iwasawa
- [ ] #4185 Fix TVP JSON export by shun-iwasawa
- [ ] #4186 Fix FrameIds Inconsistency in Level Strip Commands by shun-iwasawa
- [ ] #4187 Fix build with clang 13: no member named 'copy' in namespace 'std' by rozhuk-im
- [ ] #4190 Note level column enhancement by shun-iwasawa
- [ ] #4192 (new) OpenEXR I/O by shun-iwasawa
- [ ] #4194 Fix pressing Shift key loses focus when renaming cell by shun-iwasawa
- [ ] #4195 Project Settings-aware Frame Number Field Width by shun-iwasawa
- [ ] #4196 Xsheet PDF Export: Tickmark breaks continuous line by shun-iwasawa
- [ ] #4197 Enhanced Flipbook playback by shun-iwasawa
- [ ] #4199 Packaging Opentoonz for Fedora Distribution by dherrerace
- [ ] #4200 (Enhanced) FFMPEG GIF Export enhancements by justburner
- [ ] #4202 Fixed Flipbook wobbling when dragging while playing by shun-iwasawa
- [ ] #4203 Modify Export Xsheet PDF feature by shun-iwasawa
- [ ] #4205 (Enhanced) Multi-Thread FFMPEG and responsive finalizing window by justburner
- [ ] #4207 Fix margin of Directional Blur Fx Iwa by shun-iwasawa
- [ ] #4208 Tile Fx Iwa : a new "Image Size" option for the Input Size parameter by shun-iwasawa
- [ ] #4209 A new option for the Fractal Noise Fx Iwa : Conical Transform by shun-iwasawa
- [ ] #4211 Appveyor: update OpenCV to v4.5.5 by shun-iwasawa
- [ ] #4213 Fix various source typos by luzpaz
- [ ] #4214 (new) "Implicit hold" move by Shift+dragging cells by shun-iwasawa
- [ ] #4215 Fix various typos + translate some comments to EN by luzpaz
- [ ] #4216 Fix undo of moving cells with Shift+Ctrl by shun-iwasawa
- [ ] #4217 Zoom in/out and fit floating panel geometry commands
- [ ] #4218 Fix backtab key to work for moving styles shortcut scope by shun-iwasawa
- [ ] #4222 and - [ ] #4224 RGB sliders behaving like CSP/Krita, Hex editbox and various bugfixes by justburner (with modifications) by shun-iwasawa
- [ ] #4225 Fix crash after starting a pen stroke from inactive window by justburner
- [ ] #4227 Fix implicit hold cell dragging
- [ ] #4228 Fix crashes when using Type tool by shun-iwasawa
- [ ] #4232 (new) Hex color names editor by justburner
- [ ] #4233 Stop motion play sound on capture and deciseconds resolution by justburner
- [ ] #4234 Fix conical fractal noise with offset by shun-iwasawa
- [ ] #4235 Tahoma2D Motion Path data compatibility by manongjohn
- [ ] #4236 Fix dynamic conical fractal noise by shun-iwasawa
- [ ] #4241 (Enhanced) Raster level frame number format & PNG for new Raster level by shun-iwasawa
- [ ] #4242 (Enhanced) Style Editor: Move "toggle orientation" button in the menu by shun-iwasawa
- [ ] #4244 Stop motion patch for non-windows platforms by justburner
- [ ] #4247 Fix saving tlv by shun-iwasawa
- [ ] #4248 Fix crash on saving scene containing missing palette level by shun-iwasawa
- [ ] #4250 Camera calibration for the Camera Capture feature by shun-iwasawa
- [ ] #4252 Fix crash on undoing tool by shun-iwasawa
- [ ] #4252 Fix crash on undoing tool by shun-iwasawa
- [ ] #4256 Fix Stage Schematic Column (Right click) crash by justburner
- [ ] #4256 Fix Stage Schematic Column (Right click) crash by justburner
- [ ] #4257 Fix output file name for movie format by shun-iwasawa
- [ ] #4257 Fix output file name for movie format by shun-iwasawa
- [ ] #4258 Revert changing pinned center by shun-iwasawa
- [ ] #4261 (new) Rhubarb integration (Auto Lip-sync) by justburner
- [ ] #4263 Update translation files for v1.6 (see translations)
- [ ] #4263 Update translation files for v1.6 by shun-iwasawa  
- [ ] #4264 Fix viewer playback by shun-iwasawa
- [ ] #4264 Fix viewer playback by shun-iwasawa 
- [ ] #4265 Fix fx gadget picking by shun-iwasawa
- [ ] #4265 Fix fx gadget picking by shun-iwasawa 
- [ ] #4268 Fix GIF rendering on older versions by justburner
- [ ] #4268 Fix GIF rendering on older versions by justburner 
- [ ] #4269 Fix Stage Schematic Column (Right click) now w/Context Menu by justburner
- [ ] #4269 Fix Stage Schematic Column (Right click) now w/Context Menu by justburner 
- [ ] #4271 Initializing a missing member by justburner
- [ ] #4271 Initializing a missing member by justburner
- [ ] #4276 Fix cell mark default names to be translatable by shun-iwasawa
- [ ] #4276 fix cell mark default names to be translatable by shun-iwasawa 
- [ ] #4277 Fix crash on switching scenes while selecting raster level frame by shun-iwasawa
- [ ] #4277 Fix crash on switching scenes while selecting raster level frame by shun-iwasawa 
- [ ] #4278 Fix file browser assertion failure by shun-iwasawa
- [ ] #4278 Fix file browser assertion failure by shun-iwasawa 
- [ ] #4279 Fix crash on creating a zerary fx in the camera column by shun-iwasawa
- [ ] #4279 Fix crash on creating a zerary fx in the camera column by shun-iwasawa 
- [ ] #4280 Fix crash on cleaning up zerary column by shun-iwasawa
- [ ] #4280 Fix crash on cleaning up zerary column by shun-iwasawa 
- [ ] #4281 Fix crash on rendering PaletteFilter Fx (and other fxs) with hyphen by shun-iwasawa
- [ ] #4281 Fix crash on rendering PaletteFilter Fx (and other fxs) with hyphen by shun-iwasawa 
- [ ] #4282 Fixes toward Xsheet parenting + enhancements by justburner
- [ ] #4282 Fixes toward Xsheet parenting + enhancements by justburner 
- [ ] #4283 Fix crash on rendering ArtContour fx by shun-iwasawa
- [ ] #4283 Fix crash on rendering ArtContour fx by shun-iwasawa 
- [ ] #4284 Fix crashes with preview in Fx Settings popup by shun-iwasawa 
- [ ] #4285 Fix Particles Fx using plastic-deformed source by shun-iwasawa
- [ ] #4291 Update Spanish translation for V1.6 by Gab3d
- [ ] #4292 Fix high dpi multimonitor glitch by shun-iwasawa 
- [ ] #4293 Japanese translation v1.6 by shun-iwasawa 
- [ ] #4308 v1.6.0  by shun-iwasawa 
- [ ] #4317 Chinese translation update by jcome by shun-iwasawa 
- [ ] #4320 Fix crash on Fx Schematic  by shun-iwasawa 
- [ ] #4322 Fix tile fxs & bounding box handling  by shun-iwasawa 
- [ ] #4323 Deactivate Edit Shift mode when deactivating Shift and Trace by shun-iwasawa

Audio
Build Environment
Camera Capture/Line Testing
Canvas / Drawing
Cleanup
Control Point Editor Tool
Conversion
Effects/Schematic
File Browser
File I/O
Flipbook / Viewers
Function Editor/Schematic
Github Actions
Image Levels / Rendering / FFMPEG
Level Strip
Linux
Mypaint Brushes
Notelevels / Memos
Optimization
Palettes / Style Editor
Plastic Tool
Shortcuts
Stop Motion
Type Tool
Typos
UI
Undo
Xsheet (Export)
Xsheet / Timeline

**Comment by RodneyBaker** [comment]
Translation note:

Russian translation will likely be delayed as @beeheemooth is being rather distracted by war in Urkraine.  (Keep safe!)

@gab3d uploaded some additional spanish language translations:  REF:  #4364

cc:  @shun-iwasawa

**Comment by shun-iwasawa** [comment]
V1.6 was just released. Thank you!

**Comment by RodneyBaker** [comment]
Congratulations to all who made this v1.6 release possible!

**Comment by RodneyBaker** [comment]
As an extension of Opentoonz this relates to Opentoonz v1.6...

Tahoma2D v1.3 has been released.
Many of the improvements of Opentoonz v1.6 are included which make it even more of a useful release.

Congratulations to all involved!

https://tahoma2d.readthedocs.io/en/latest/whats_new.html

Download:  https://tahoma2d.org/download.html
