### ISSUE TITLE
Work in Progress - Current Pull Request Snapshot

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#4579]
This report is being opened to better give insight into current Pull Requests (PR) and assist those who want to contribute to Opentoonz development.  This not only to allow the creator of a Pull Request to understand thoughts related to a pull request not captured in the PR itself but to allow testers and those that wish to provide feedback a means to see at a glance which PRs are on the table and their status.

An underlying premise of this report is to emphasis a longer term look at the Opentoonz development cycle... specifically focusing more on weekly and monthly schedule but without losing the benefits of our regular 'nightly' releases which occur with the merger of each PR.

Here we might also revisit some older PRs that have been closed in order to see what in them might move forward as a concept, research area and potentially new PR.

This might not be the ideal place for this but for now it should at least provide some insight into status of current PRs.

This first snapshot is to get the process started for Novemember's development.

**Comment by RodneyBaker** [comment]
Week of 23 - 30 October

Pull Requests
- [ ] #4572 
Opened 3 days ago by [justburner](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ajustburner)
Status:  Initial testing complete.  Open for Community Feedback

- [ ] #4432 
Opened on Apr 29 by [JPUser1](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3AJPUser1)
Status:  This is a direct port from Tahoma2D
Initial Testing complete.  Additional testing and feedback required.

- [ ] #4388 
Opened on Mar 31 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)
• [Draft](https://github.com/opentoonz/opentoonz/pull/4388#partial-pull-merging)
Status:  Initial testing complete   Work in Progress open to community feedback.

- [ ] #3665 
 Opened on Jan 1, 2021 by [morevnaproject](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Amorevnaproject)
Status:  Stagnant work in progress with high potential
Minor changes would allow PR to be merged 'as is'
Longer term development anticipated to realize full Production Board feature set

Pull Request link:   https://github.com/opentoonz/opentoonz/pulls

**Comment by RodneyBaker** [comment]
Week of 31 October - 6 November

Pull Requests
- [x] #4572 by [justburner](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ajustburner)
Status:  Initial testing complete.  Merged.

- [ ] #4432 
Opened on Apr 29 by [JPUser1](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3AJPUser1)
Status:  This is a direct port from Tahoma2D
Initial Testing complete.  Additional testing and feedback required.

- [ ] #4388 
Opened on Mar 31 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)
• [Draft](https://github.com/opentoonz/opentoonz/pull/4388#partial-pull-merging)
Status:  Initial testing complete   Work in Progress open to community feedback.

- [ ] #3665 
 Opened on Jan 1, 2021 by [morevnaproject](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Amorevnaproject)
Status:  Stagnant work in progress with high potential
Minor changes would allow PR to be merged 'as is'
Longer term development anticipated to realize full Production Board feature set

Open Pull Requests:   https://github.com/opentoonz/opentoonz/pulls
Closed/Completed Pull Requests:  https://github.com/opentoonz/opentoonz/pulls?q=is%3Apr+is%3Aclosed

**Comment by RodneyBaker** [comment]
Week of 6 - 12 November (Initial Draft)

New PRs

- [ ] #4591 by [justburner](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ajustburner)
- [ ] #4590 by [justburner](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ajustburner)


Old PRs
- [ ] #4388 opened on Mar 31 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)
- [ ] #3665 opened on Jan 1, 2021 by [morevnaproject](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Amorevnaproject)

Future work:
- Potential Revert.  Investigate report of lag possibly related to Lazy Nezumi fix (See  #4432)
-  Brush Review.  Determine which MyPaint brushes (if any) might be added now that there is some brush management in Opentoonz (See #4572)

**Comment by RodneyBaker** [comment]
Week of 13 - 19 November (initial draft)

New PRs N/A

Old PRs
- [ ] #4592 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) 
- [ ] #4388 opened on Mar 31 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)
- [ ] #3665 opened on Jan 1, 2021 by [morevnaproject](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Amorevnaproject)

Future work:
- Automated github checks for Mac not working  (Nightlies are building however)
-  Brush Review.  Determine which MyPaint brushes (if any) might be added now that there is some brush management in Opentoonz (See #4572)

**Comment by RodneyBaker** [comment]
Week of 20 - 26 November (working draft)

New PRs
- [ ] #4602 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)

Old PRs
- [ ] #4592 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) 
- [ ] #4388 opened on Mar 31 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)
- [ ] #3665 opened on Jan 1, 2021 by [morevnaproject](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Amorevnaproject)

Future work:
-  Continue Brush Review.  Determine what brushes are ideal for adding now that OT has basic brush management  (See #4572)
- #4561

**Comment by RodneyBaker** [comment]
Week of 27 Nov - 3 Dec (working draft)

New PRs
- [ ] #4611 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) (See:  #3665)

Old PRs
- [ ] #4592 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) 
- [ ] #4388 opened on Mar 31 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)
- [ ] #3665 opened on Jan 1, 2021 by [morevnaproject](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Amorevnaproject) (See #4611)

Future work:
-  Continue Brush Review.  Determine what brushes are ideal for adding now that OT has basic brush management  (See #4572)
- #4561

**Comment by RodneyBaker** [comment]
Week of 4 Dec - 10 Dec (Working Draft)

New PRs
- [ ] #4633 opened by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)
- [ ] #4628 by [konero](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Akonero)
- [ ] #4626  by [andeon](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aandeon)
- [x] #4618 by [konero](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Akonero)
- [ ] #4611 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) (See:  #3665)

Old PRs
- [ ] #4592 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) 
- [ ] #4388 opened on Mar 31 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)
- [ ] #3665 opened on Jan 1, 2021 by [morevnaproject](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Amorevnaproject) (See #4611)

Considerations:
- Windows Nightlies not building
-  #4608 by [SaeedSS3](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3ASaeedSS3)
- Additional Brushes  (See #4572)
- #4561

**Comment by RodneyBaker** [comment]
Week of 11 Dec - 17 Dec (Working Draft)

New PRs

Old PRs
- [ ] #4592 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) 
- [ ] #4388 opened on Mar 31 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)

Considerations:
- Mac nightly builds are not propagating to the nightlies listing
-  #4608 by [SaeedSS3](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3ASaeedSS3)
- Additional Brushes  (See #4572)
- #4561

See also:  Opensource [IwaWarper](https://opentoonz.github.io/e/download/iwawarper.html) program by @shun-iwasawa

**Comment by RodneyBaker** [comment]
Week of 18 Dec - 24 Dec (Working Draft)

New PRs

Old PRs
- [ ] #4592 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) 
- [ ] #4388 opened on Mar 31 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)

Considerations:
-  #4608 by [SaeedSS3](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3ASaeedSS3)
- Additional Brushes  (See #4572)
- #4561

See also:  Release of opensource [IwaWarper](https://opentoonz.github.io/e/download/iwawarper.html) program by @shun-iwasawa

**Comment by RodneyBaker** [comment]
Week of 25 Dec - 31 Dec (Working Draft)

New PRs
- [ ] #4678 by [se7enstar25](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ase7enstar25)

Old PRs
- [ ] #4670 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)
- [ ] #4668 by [konero](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Akonero)
- [ ] #4592 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) 
- [ ] #4388 opened on Mar 31 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)

Considerations:
- Additional Brushes  (See #4572)
- #4561

See also:  Release of opensource [IwaWarper](https://opentoonz.github.io/e/download/iwawarper.html) program by @shun-iwasawa

**Comment by RodneyBaker** [comment]
Week of 1 Jan - 7 Jan (Working Draft)  Happy New Year!

New PRs

Old PRs
- [ ] #4681 by [justburner](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ajustburner)
- [ ] #4592 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) 
- [ ] #4388 opened on Mar 31 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)

Considerations:
- Additional Brushes  (See #4572)
- #4561

See also:  Release of opensource [IwaWarper](https://opentoonz.github.io/e/download/iwawarper.html) program by @shun-iwasawa
