### ISSUE TITLE
2023 Pull Request Snapshot

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#4694]
Week of 1 Jan - 7 Jan  Happy New Year!

New PRs

Old PRs
- [x] opentoonz/opentoonz#4681 by [justburner](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ajustburner)
- [ ] opentoonz/opentoonz#4592 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) 
- [ ] opentoonz/opentoonz#4388 opened on Mar 31 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)

Considerations:
- Additional Brushes  (See opentoonz/opentoonz#4572)
- opentoonz/opentoonz_docs#133

Previous snapshot: #4693

See also:  Release of opensource [IwaWarper](https://opentoonz.github.io/e/download/iwawarper.html) program by @shun-iwasawa

**Comment by RodneyBaker** [comment]
Week of 8 Jan - 14 Jan (Working Draft) 

New PRs
- [ ] #4698 by [manongjohn](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Amanongjohn)

Old PRs
- [ ] opentoonz/opentoonz#4592 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) 
- [ ] opentoonz/opentoonz#4388 opened on Mar 31 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)

Considerations:
- Additional Brushes  (See opentoonz/opentoonz#4572)
- opentoonz/opentoonz_docs#133

See also:  Release of opensource [IwaWarper](https://opentoonz.github.io/e/download/iwawarper.html) program by @shun-iwasawa

**Comment by RodneyBaker** [comment]
Week of 15 Jan - 21 Jan (Working Draft) 

New PRs

Old PRs
- [ ] opentoonz/opentoonz#4592 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) 
- [ ] opentoonz/opentoonz#4388 opened on Mar 31 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)

Considerations:
- Additional Brushes  (See opentoonz/opentoonz#4572)
- opentoonz/opentoonz_docs#133

See also:  Opensource [IwaWarper](https://opentoonz.github.io/e/download/iwawarper.html) by @shun-iwasawa (Mac build support is currently being added)

**Comment by RodneyBaker** [comment]
Week of 22 Jan - 28 Jan (Working Draft) 

New PRs
- [ ] #4716 by [justburner](https://github.com/opentoonz/opentoonz/issues q=is%3Apr+is%3Aopen+author%3Ajustburner)

Old PRs
- [ ] #4608 requested on Nov 21, 2022 by [SaeedSS3](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3ASae) _Draft document provided_
- [ ] opentoonz/opentoonz#4592 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) 
- [ ] opentoonz/opentoonz#4388 opened on Mar 31 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)

Considerations:
- How best to add additional brushes?  (See opentoonz/opentoonz#4572)
- Can Opentoonz Docs be utilized to clear main repo of non developmental discussions?  opentoonz/opentoonz_docs#133

Additional:
Update of opensource [IwaWarper](https://opentoonz.github.io/e/download/iwawarper.html) by @shun-iwasawa (Mac build support is currently being added)

**Comment by RodneyBaker** [comment]
Week of 29 Jan - 4 Feb (Working Draft) 

New PRs
- [ ] #4731 by [justburner](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ajustburner)

Old PRs
- [ ] #4724 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) (Draft)
- [ ] #4723 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick)
- [ ] #4608 requested on Nov 21, 2022 by [SaeedSS3](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3ASae) _Draft document provided_
- [ ] opentoonz/opentoonz#4592 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) 
- [ ] opentoonz/opentoonz#4388 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)

Considerations:
- How best to add additional brushes?  (See opentoonz/opentoonz#4572)
- Can Opentoonz Docs be utilized to clear main repo of non developmental discussions?  opentoonz/opentoonz_docs#133

Additional:
Update of opensource [IwaWarper](https://opentoonz.github.io/e/download/iwawarper.html) by @shun-iwasawa (Mac build support is currently being added)

**Comment by RodneyBaker** [comment]
Week of 5 Feb - 11 Feb (Working Draft) 

New PRs
- [ ] #4739 by [grillo-delmal](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Agrillo-delmal)

Old PRs
- [ ] #4724 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) (Draft)
- [ ] #4723 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick)
- [ ] #4608 requested on Nov 21, 2022 by [SaeedSS3](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3ASae) _Draft document provided_
- [ ] opentoonz/opentoonz#4592 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) 
- [ ] opentoonz/opentoonz#4388 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)

Considerations:
- How best to add additional brushes?  (See opentoonz/opentoonz#4572)
- Can Opentoonz Docs be utilized to clear main repo of non developmental discussions?  opentoonz/opentoonz_docs#133

Additional:
Update of opensource [IwaWarper](https://opentoonz.github.io/e/download/iwawarper.html) by @shun-iwasawa (Mac build support is currently being added)

**Comment by RodneyBaker** [comment]
Week of 12 Feb - 18 Feb (Working Draft) 

New PRs

Old PRs
- [ ] #4724 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) (Draft)
- [ ] #4723 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick)
- [ ] #4608 requested on Nov 21, 2022 by [SaeedSS3](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3ASae) _Draft document provided_
- [ ] opentoonz/opentoonz#4592 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) 
- [ ] opentoonz/opentoonz#4388 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)

Additional:
- Can Opentoonz Docs be utilized to clear main repo of non developmental discussions?  opentoonz/opentoonz_docs#133
Update of opensource [IwaWarper](https://opentoonz.github.io/e/download/iwawarper.html) by @shun-iwasawa (Mac build support is currently being added)

**Comment by RodneyBaker** [comment]
Week of 26 Feb - 4 Mar (Working Draft)

New PRs
- [ ] #4756 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)

Old PRs
- [ ] #4724 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) (Draft)
- [ ] #4723 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick)
- [ ] #4608 requested on Nov 21, 2022 by [SaeedSS3](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3ASae) _Draft document provided_
- [ ] opentoonz/opentoonz#4592 by [flurick](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Aflurick) 
- [ ] opentoonz/opentoonz#4388 by [shun-iwasawa](https://github.com/opentoonz/opentoonz/issues?q=is%3Apr+is%3Aopen+author%3Ashun-iwasawa)

Additional:

**Comment by RodneyBaker** [comment]
Closing this PR snapshot as not needed going into the v1.7 release.
Please refer to the PR listing itself:  https://github.com/opentoonz/opentoonz/pulls
