### ISSUE TITLE
v1.7 Bug Hunt

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#4714]
In the Discussion on OpenToonz development (#2746), stability was mentioned and this Bug Hunt is designed to place a focus on that aspect of development.  The best place to provide feedback on bugs is in individually reported issues but here we want to get a larger view of issues and patterns  impacting stability in Opentoonz.

### Crash ([LINK](https://github.com/opentoonz/opentoonz/issues?q=is%3Aopen+is%3Aissue+label%3ACrash))
All issues currently tagged with 'crash'

### Bugs  ([LINK](https://github.com/opentoonz/opentoonz/issues?q=is%3Aopen+is%3Aissue+label%3ABug))
All issues currently tagged as 'bug'

### Troubleshooting  ([LINK](https://groups.google.com/forum/#!categories/opentoonz_en/troubleshooting))  
This Links to Opentoonz Google Group (English)
The Opentoonz forum is a good place to highlight and resolve issues that approach being a bug or crash but need assistance in resolving such as determining exact steps to reproduce the bug or crash.  Most issues also have workarounds so while awaiting the resolution of a problem it will be good to use known workarounds

There is also currently a 'troubleshooting' tag where most responses tend to be referrals to other Opentoonz venues such as the OT Google Groups, disords, reddits, facebook, etc.  ([LINK to troubleshooting reports](https://github.com/opentoonz/opentoonz/issues?q=is%3Aopen+is%3Aissue+label%3Atroubleshooting))

### User Interface ([UI](https://github.com/opentoonz/opentoonz/issues?q=is%3Aopen+is%3Aissue+label%3AUI)) and Workflow issues

These are frustrating and in need of optimization but don't generally meet the criteria of being a bug.  They are however still important and may even provide vital clues to why a process isn't functioning optimally.  Report these issues with the same attention to detail as you would a bug or crash report but be patient as priorities will favor a bug.

### **Want to help?**
All issues are important but stability highly depends on finding and resolving bugs; especially those that lead to crashes, corrupt data and interference with production.  When you have time read through the issue titles and see if any stand out.   Your experience might provide a vital piece in solving the problem.  

When bug hunting:
- Look for other reported issues that are similar or the same as yours.  Your feedback might help resolve the problem for everyone.  
- Fill in the issue template provided when opening an issue as best as you can.  Help others resolve your problem.
- Look for precise steps that can be listed to replicate the bug.  
- Report specific information about computer, operating system and anything that might help isolate the bug.  Do you have access to another computer?  Does the problem happen there also?
- Monitor your report and update it as necessary.  
- Finally, close your report (and thank those who helped) when the problem is resolved.  

As always, thank you for your feedback and for helping our community keep Opentoonz stable and reliable.

**Comment by RodneyBaker** [comment]
I see that Qt 6.4.3 has been released with over 300 bugfixes.

There is a fairly good chance that a few of those impact Opentoonz.

REF:  https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.4.3/release-note.md

**Comment by RodneyBaker** [comment]
We are entering the final stages before v1.7 roll out where with features locked down we can focus on bug fixes.
Here are some of the most recently reported bugs:

- [ ] #4784 by JPJammin
- [ ] #4781 by Milkmoo
- [ ] #4779 by deathchimera
- [ ] #4764 by Meister3
- [ ] #4738 by grillo-delmal
- [ ] #4737 by gab3d
- [ ] #4704 by F-Burning
- [ ] #4696 by age3rcm
- [ ] #4691 by KaseyFarron
- [ ] #4688 by nukeCrayon
- [ ] #4687 by nukeCrayon
- [ ] #4651 by KaseyFarron
- [ ] #4645 by AlmenPils
- [ ] #4638 by Lantau42
- [ ] #4630 by TenebrisLuxx
- [ ] #4621 by openanim
- [ ] #4619 by openanim
- [ ] #4617 by melieconiek
- [ ] #4607 by F-Burning
- [ ] #4603 by thegrayoutlaw
- [ ] #4597 by openanim
- [ ] #4559 by Juan8diegoO
- [ ] #4556 by JBSedich
- [ ] #4552 by beeheemooth
- [ ] #4538 by bencresty
