### ISSUE TITLE
Multicolor single layer drawing passes - mark a style as an 'R' - rough pass linework

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#499]
Basically this is a feature request for a workflow approach for drawing cleanup in tvpaint. It is the bread and butter of tvpaint. I explained how it works here: https://github.com/callaa/Drawpile/issues/191
And the developer actually implemented it!

I am going to adapt my proposal to the design of opentoonz!

**What is it:**
One way to be able to sketch, clean up and ink a drawing without the need to use multiple layers is to do it like tvpaint - 
https://vimeo.com/57043308  (see at 5:28)

It has 4 compositing inks that can be erased individually - red, cyan, green and black.
The user sketches in one color (cyan), then for the second pass sketches with another color(black) over the old color. Then with a single click of a button, he erases the first color that is underneath (cyan) and gets a clean drawing with only the second pass (black).
If he wants to further refine the drawing, the artist turns the cleaned sketch he has (black ink) into a another color (cyan) again - with a single click. Then repeats the process.
![tvpaintrgbpanelsketch](https://cloud.githubusercontent.com/assets/6495061/7229931/cbd98ab8-e771-11e4-82bf-d5fe5d954d58.png)

This is really a fantastic way to work on a single layer and mimics the traditional animator workflow as well! In traditional animation animators sketch with the  cyan pencil, then sketch with the black pencil on top of the cyan. Then erase the cyan pencil with an eraser that only affects it - or by photocopying - the  copy machines can't see the cyan color. Some use cyan, others use red.
https://en.wikipedia.org/wiki/Non-photo_blue
https://en.wikipedia.org/wiki/Clean-up
.
Tvpaint has 4 colors to do this workflow, but you can really get away with two - cyan and black.

In order for this workflow approach to work, we need just a few elements added- because opentoonz already has the ingredients to make it happen!
-  'Draw Behind' mode for the brush tool (toonz raster levels) - when in this mode, strokes that you make are drawn behind the already existing pixels on the level. 
  We already have that in opentoonz!
  ![capture](https://cloud.githubusercontent.com/assets/6495061/16288309/58ced47e-38e2-11e6-90a6-7914987b9564.PNG)
- Palette window> right click on a style> remove all lines - command to erase all the lines on the active level that have the style that the user right clicked on. This can be our 'erase by color'. Opentoonz can already do this with a workaround:
  
  right click on a style>delete> delete styles,lines and areas (undoable)
  Undo

This will delete all of the linework with that style, but also delete the style from the palette. The undo will then bring back the style but not the linework. 

Having it as a right click command instead would allow to delete all the linework with the style,but be able to undo that step.
- colorize to style - this is another feature that opentoonz already (sort of) has, but it is not a single command like in tvpaint. To reproduce it:
  Bucket tool> mode:lines, type rectangular  and then box select the entire screen. It would be nice to have it as a single command in the style right click menu of a style - 'colorize level to this style'

How opentoonz can actually make these features better than tvpaint:
- instead of erasing the sketch pass styles, opentoonz could hide it's pixels and make the bucket tool ignore it. This could be done by right clicking on the style> set as rough pass
  ![roughpassstyle](https://cloud.githubusercontent.com/assets/6495061/16288523/a34f8618-38e4-11e6-8768-3a56283b8b4c.png)

When set to rough pass, the lines of that style visually disappear from the level, but the information is still there and can be viewed at a later stage again by removing the "R" tag. All lines with an 'R' tagged style are also ignored by the bucket tool and other tools- they are completely disabled - both in visibility and for tools when the R tag is on their style.
The point of being able to put that tag on a style really is to disable it, but keep its information (lines, fills,etc)

**Comment by Rayek** [comment]
I think this would be a brilliant addition.

**Comment by blurymind** [comment]
Do you think the name of the command is clear enough?
"set as rough pass" - with an "R" indicator when it is tagged on a style?
(all line work and fills using the style are disabled completely in visibility and to tools - they wont interfere with cleanup work that way!)

Alternative names could be:
"Disable style" - with an "X" as an indicator that the style is in a disabled state.
or
"Mute style" - with an "m" as an indicator.

**Comment by blurymind** [comment]
To summarize all the features requested here in this proposal - for new right click commands for the styles in the palette window to aid multicolor sketching:

- [ ] Set as rough pass - puts a rough pass (R) tag on a style. Styles with this tagged are seen by the software as sketch or rough pass that should be ignored by the bucket tool, disabled in visibility and to final render. They are seen as production history.

- [ ] Colorize level to this style - colorizes the currently active level's line work to the style that was right clicked on. This is a one click solution that does it - so we dont have to do the workaround.

- [ ] Delete Lines - Deletes the

**Comment by shun-iwasawa** [comment]
Regarding the third requested feature:
OpenToonz already has a command for deleting lines with specified style index - "Delete Lines" command is exactly for such purpose.
Please note that you cannot use "Delete Lines" command to other than toonz raster levels. If you use this command to vector levels (with selecting level strip frame, it fails to interrupt executing the command), OpenToonz will crash. I found this crash bug right now!

**Comment by blurymind** [comment]
@shun-iwasawa Thank you for sharing. I now found it in the x-sheet menu.
The function only works on toonz raster levels however.
It is possible to delete both raster and vector lines with my workaround

**Comment by blurymind** [comment]
In any case the "delete lines" command will be much less important if OT gets a "Rough pass" tagging feature for styles. It is very likely that many people will prefer to keep their sketching pass lines instead of deleting them. It would be one advantage to have overt tvpaint where you have to always delete them before rendering!

**Comment by RodneyBaker** [comment]
No update since May 2017 for this feature request.
Recommend revisiting.

**Comment by RodneyBaker** [comment]
The bug/crash related issues identified while examining this set of features related to using 'Delete Lines' function appear to be resolved.

**Comment by blurymind** [comment]
the request is for style tagging - to mark styles that are not going to be rendered by OT

**Comment by RodneyBaker** [comment]
I'll add this to the mix... mostly for those looking in wondering how all this reporting stuff works.

The basic rule of "no feature requests" on Opentoonz github doesn't apply as strictly to active developers.  It's my understanding that particular rule was created to assist developers in their effort to work on Opentoonz with minimal distraction.  

A means around this restriction is to fork/branch Opentoonz and create a space where the rules allow for feature requests.  For general discussion on features there is always the Opentoonz Forum and the various other resources (such as discord) also.

As an active developer of Opentoonz the choice to Open/Close is largely yours.  Discussion can of course continue in closed topics for those areas of interest that need to go on hiatus.

**Comment by RodneyBaker** [comment]
Regarding the feature in question I'll note the basic approach I use to achieve similar result.

Set up two or more columns in xsheet/timeline and adjust the color/tint and transparency to the desired state for roughing out work.   Try gray.  Try original color faded.  See what works best for you.

The tint and transparency can be made to never appear, appear only in real time and/or in preview/final render.

If desired the user can draw/paint with only one color (say black) and have that color change to other color depending on where the lines are drawn.  In this way it is possible to create custom onionskinning workflows.  

As an aside:  The Palette Filter FX can also be used to strip specific colors out of the workflow so that they will not render to preview/final. 

That's one poor man's way of setting up a rough pass methodology.
I'd love to hear other approaches.

**Comment by RodneyBaker** [comment]
It's important to note that some of the milestone features described have been achieved at this point.  For example:

- [ ]  'Draw Behind' mode for the brush tool (toonz raster levels) - when in this mode, strokes that you make are drawn behind the already existing pixels on the level.

Note that this toonz raster feature has "Under All", "Over All" and "Palette Order". 

See PR #1849 for more information on brush stroke order.

**Comment by RodneyBaker** [comment]
This is a Work in Progress slipping to the 2019 development cycle.

**Comment by RodneyBaker** [comment]
If there is still a crash/bug related to this feature request it should be extracted out into a separate report.  Untagging as Crash/Bug for the moment.

cc:  @turtletooth

**Comment by RodneyBaker** [comment]
Closing as slipping to 2020 Development cycle and beyond... as no one is currently attached and actively developing this feature.  Anticipate reopening on the other side of 2019 after v1.4 release.  

This would be a good opportunity to thoroughly document any current "ugly workarounds" as well as other workflows achieving similar results.  

Tagging as 'roadmap' to highlight current level of interest.
